[#10581] Add top level domain hint for invalid email error
TEAMMATES/teammates pull request #10633
Opened 2020-08-23 15:46 UTC by moziliar

Fixes #10581

2020-09-16 12:01 UTC, madanalogy requested changes
Seems like your code isn't passing the lint or component tests on the CI. You need to resolve those issues. Do ask for help if you need it. 

Also, once you're done making changes, just remember that you'll need to re-request for a review. Otherwise, your PR will not be attended to. Feel free to tag me with a mention if you have problems requesting for a review.

2020-09-16 12:11 UTC, moziliar commented
> Seems like your code isn't passing the lint or component tests on the CI. You need to resolve those issues. Do ask for help if you need it.
> 
> Also, once you're done making changes, just remember that you'll need to re-request for a review. Otherwise, your PR will not be attended to. Feel free to tag me with a mention if you have problems requesting for a review.

@madanalogy Sorry for leaving this PR for quite a while. I was told that everyone is supposed to do only 1 trivial (first-timer) issue, hence I held off from updating this PR. But I will just finish this off first then.

2020-09-18 12:10 UTC, madanalogy approved these changes
LGTM

2020-09-19 08:45 UTC, t-cheepeng approved these changes
LGTM

2020-09-19 13:00 UTC, wkurniawan07 requested changes

2020-09-19 13:00 UTC, wkurniawan07 commented on src/main/java/teammates/common/util/FieldValidator.java
> +                    + "with a top domain address like .com. "
"top domain" has no meaning. Top-level domain (TLD) is the universally understood term for what is mentioned here.

2020-09-24 14:19 UTC, madanalogy commented
@moziliar there seems to have been some changes to the test files, please help to resolve the conflicts thanks

2020-09-25 03:26 UTC, madanalogy approved these changes

2020-09-25 03:26 UTC, merged