[#10664]Student trying to access non-existent session: give a better error message
TEAMMATES/teammates pull request #10733
Opened 2020-09-29 13:22 UTC by sjkadali

Fixes ##10664

**PR Checklist**

Ensure that you have:
- [ y] Read and understood our PR guideline: https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr
  - [ y] Added the issue number to the "Fixes" keyword above
  - [y ] Titled the PR as specified in the abovementioned document
- [y] Made your changes on a branch other than `master` and `release`
- [y ] Gone through all the changes in this PR and ensured that:
  - [ ] They addressed one (and only one) issue
  - [ y] No unintended changes were made
- [ ] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

2020-10-01 06:12 UTC, ChooJeremy commented
Hi @sjkadali, have you tested this locally? Does the error message appear as expected?

2020-10-02 14:51 UTC, sjkadali commented
@ChooJeremy , when I tested this locally, it showed the below page with error message.

![Screenshot from 2020-10-02 10-45-33](https://user-images.githubusercontent.com/39105848/94937021-0aa69d00-049d-11eb-8e5a-fc670989c7bc.png)

2020-10-03 03:04 UTC, damithc requested changes

2020-10-03 03:04 UTC, damithc commented on src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
> +            'The session does not exist (most likely deleted by instructor after the submission link was sent).');
Change as `by the instructor`

2020-10-03 04:17 UTC, ChooJeremy commented
> 
> 
> Hi @sjkadali, have you tested this locally? Does the error message appear as expected?

That's odd, when I tested this the redirect occurs immediately (no chance for an error message to appear), how are you testing this exactly?

2020-10-05 12:48 UTC, sjkadali commented on src/web/app/pages-session/session-submission-page/session-submission-page.component.ts
> +            'The session does not exist (most likely deleted by instructor after the submission link was sent).');
ok

2020-10-05 13:17 UTC, sjkadali commented
> > Hi @sjkadali, have you tested this locally? Does the error message appear as expected?
> 
> That's odd, when I tested this the redirect occurs immediately (no chance for an error message to appear), how are you testing this exactly?

@ChooJeremy, i had started the dev server in the background using the command,  ./gradlew appengineRun to access the admin page at http://localhost:8080/web/admin/home.  Then started Front-end dev server using the command, npm run start.  
On updating the error message, logged in as student at http://localhost:4200/web/student/home. Clicked on an existing submission's View Submission button to view the submission. On changing the link to point to a non-existing session,  it redirects to the student home page , but the updated error message is shown.

2020-10-05 19:10 UTC, sjkadali commented
@damithc , Have addressed the requested changes. Please review. Thanks!

2020-10-06 02:10 UTC, ChooJeremy approved these changes
Ah, I see. Nice, so this solves the issue of the partially loaded page as well. LGTM

2020-10-06 02:30 UTC, damithc approved these changes
The message is OK.

2020-10-06 12:38 UTC, merged