[#10645] Admin search results: show more info
TEAMMATES/teammates pull request #10877
Opened 2020-12-13 17:54 UTC by g-lilian

Fixes #10645

Finished the first part of the suggestion in the issue by linking student name to course details page in the admin search results.

*Ready for review

2020-12-13 17:57 UTC, g-lilian commented
Strange, the top 3 commits were from my previous PR (already merged). I am not sure why it is appearing in the commit history.

2020-12-15 14:53 UTC, rrtheonlyone commented
@g-lilian you can follow the below steps to remove those commits:

```
git fetch upstream
git pull --rebase upstream master
git log --online #check commits are gone 
git push --force origin 10645
```

2020-12-16 07:19 UTC, g-lilian commented
> @g-lilian you can follow the below steps to remove those commits:
> 
> ```
> git fetch upstream
> git pull --rebase upstream master
> git log --oneline #check commits are gone 
> git push --force origin 10645
> ```

Thanks. I've removed those commits.

2020-12-17 04:07 UTC, t-cheepeng requested changes

2020-12-17 04:07 UTC, t-cheepeng commented on src/web/services/link.service.ts
> +  INSTRUCTOR_COURSE_DETAILS_PAGE: string = '/instructor/courses/details';
typo? 

`COURSES` instead of `COURSE`

2020-12-17 04:20 UTC, g-lilian commented on src/web/services/link.service.ts
> +  INSTRUCTOR_COURSE_DETAILS_PAGE: string = '/instructor/courses/details';
Noted and fixed!

2020-12-18 03:09 UTC, t-cheepeng approved these changes

2020-12-18 14:09 UTC, ccyccyccy reviewed
Is the link supposed to be a masquerade link? SInce the link currently doesn't work as an admin.
![image](https://user-images.githubusercontent.com/32454748/102623501-8ac7cf00-417d-11eb-9677-0f8eb043ffe4.png)

2020-12-18 14:54 UTC, g-lilian commented
> Is the link supposed to be a masquerade link? SInce the link currently doesn't work as an admin.
> ![image](https://user-images.githubusercontent.com/32454748/102623501-8ac7cf00-417d-11eb-9677-0f8eb043ffe4.png)
Oh.. How does the masquerade work? It linked correctly when I signed in as admin using the dev server.

2020-12-19 08:12 UTC, ccyccyccy commented
When logged in as administrator, masquerade mode can also be used to impersonate instructors and students by adding `user=username` to the URL e.g `http://localhost:8080/web/student/home?user=johnKent.`

> Link student name to the course of that student in the course instructor (i.e., masquerade as the instructor of the course) 

The issue mentions that you need to append the query param.

Below is what I am seeing. Can you provide a gif if your solution works currently?

![Screen Recording 2020-12-19 at 3 58 15 PM](https://user-images.githubusercontent.com/32454748/102684515-3c194400-4214-11eb-8178-df7fca9b05e1.gif)

2020-12-20 03:38 UTC, g-lilian commented
Yup here is my gif. As you can see in the browser address bar, the course details page is generated and I can view it as an admin.
![adminsearch](https://user-images.githubusercontent.com/50647023/102704540-c4045a00-42b7-11eb-9d8f-ea81383ff890.gif)

2020-12-20 04:18 UTC, ccyccyccy commented
Might be something wrong at my end then. @t-cheepeng Can you confirm that it works without needing masquerade mode?

2020-12-20 12:34 UTC, wkurniawan07 commented
@ccyccyccy there's nothing wrong on your side. The link definitely needs masquerade mode. In fact, it is the main difficulty of the issue: finding out which instructor to be masqueraded as.

@g-lilian the logged in user you're using must be the instructor of the course being visited (`test-course-id`) and at the same time being admin, that's why you could get it to work without masquerade mode.

@damithc how would linking to the course details page help? I suspect you're thinking of some other page but it came across as that.

2020-12-20 12:46 UTC, g-lilian commented
@wkurniawan07 
Oh, I see. So that's why it works for me. Does masquerade mode just involve appending `user=username` as a param? i.e. the generated link should instead be `.../courses/details?courseid=test-course-id&user=test-user` where test-user must be the instructor of the course being visited?

2020-12-20 16:12 UTC, damithc commented
> @damithc how would linking to the course details page help? I suspect you're thinking of some other page but it came across as that.

Good point. The page I (as the admin) need to reach can vary based on the problem I'm trying to troubleshoot on behalf of a student user. For example, if a student says he can't see any team members, I need to check the 'student list' page to see if the team ID of this student vary slightly from other team members. The important thing is I should be able to switch easily to the masquerade mode for the instructor of the student. The exact page doesn't actually matter. Perhaps, linking to the student name to the 'student list' page is more intuitive?

2020-12-20 17:48 UTC, wkurniawan07 commented
> linking to the student name to the 'student list' page is more intuitive

That's even worse because student list page is essentially a combination of multiple tables in the course details page?

2020-12-21 02:36 UTC, damithc commented
> > linking to the student name to the 'student list' page is more intuitive
> 
> That's even worse because student list page is essentially a combination of multiple tables in the course details page?

Worse in what sense?
How about 'student details' page of that student? That's specifically a page related to the student.

2020-12-21 03:11 UTC, t-cheepeng commented
@ccyccyccy
Tested and the link does requires masquerade mode as mentioned

2021-05-16 07:56 UTC, damithc commented
Any chance of salvaging this PR? Functionality-wise, I'm fine as long as it goes to an instructor page of the same course. My primary objective is to be able to masquerade an instructor of that course with one click. The current behavior of this PR seems good enough for that purpose.

2021-05-16 12:49 UTC, wkurniawan07 commented
> My primary objective is to be able to masquerade an instructor of that course with one click. The current behavior of this PR seems good enough for that purpose.

No. The current PR as is does not even introduce masquerading.

2021-05-16 14:08 UTC, damithc commented
> No. The current PR as is does not even introduce masquerading.

Right. I misinterpreted @ccyccyccy 's comment.

Let's close this PR in that case so that someone else can take shot at it.

2021-05-16 14:08 UTC, closed without merging