[#10564] Feedback session question options: unable to select text by dragging cursor
TEAMMATES/teammates pull request #10884
Opened 2020-12-17 09:52 UTC by AdithyaNarayan

Fixes #10564 

**Outline of Solution**
- Extracted the drag button from the `rank-options-field` component and placed in in the `rank-options-question-edit-details-form`
- Extracted the drag button from the `constsum-options-field` component and placed in in the `constsum-options-question-edit-details-form`

**Expected Behaviour of the drag options**

![working gif](https://user-images.githubusercontent.com/20930155/102471657-7a2f3000-407b-11eb-893f-a33f6f326551.gif)

2020-12-27 04:12 UTC, niqiukun requested changes
Try to avoid making unnecessary UI changes here. For example, the input bar used to be longer and there is no space between the handle and the input bar before this PR is applied.

Original:
![image](https://user-images.githubusercontent.com/5328196/103163693-5f5b7900-483c-11eb-844b-d54ac433e9cd.png)

After change:
![image](https://user-images.githubusercontent.com/5328196/103163718-b06b6d00-483c-11eb-8931-14cb5ae52493.png)

2021-01-14 08:23 UTC, AdithyaNarayan commented
Oh sorry! I think I have fixed it now!

2021-01-18 04:43 UTC, hcwong approved these changes
Looks fine to me, except for that one comment

2021-01-18 04:43 UTC, hcwong commented on src/web/app/components/question-types/question-edit-details-form/constsum-options-question-edit-details-form.component.html
> +        <div class="row margin-bottom-20px padding-left-12px d-flex" *ngFor="let option of model.constSumOptions; let i = index;
is `d-flex` necessary? I don't see any UI changes when I remove that CSS class.

2021-01-21 01:55 UTC, madanalogy approved these changes
LGTM

2021-01-21 06:57 UTC, madanalogy commented
@niqiukun need your approval on this since you requested changes

2021-01-21 07:28 UTC, niqiukun approved these changes
LGTM!

2021-01-25 15:56 UTC, merged