[#10928] Add script to list active instructors within a period
TEAMMATES/teammates pull request #10947
Opened 2021-02-05 07:52 UTC by daongochieu2810

Fix #10928
Solution outline:
- Filter feedback sessions based on given start and end times
- Get creator email from filtered sessions and print them

2021-02-07 03:35 UTC, damithc commented on src/client/java/teammates/client/scripts/ListActiveInstructors.java
> +        long endTime = 1612108800000L;
I'll have to update these manually. So, use a human editable format for the dates :-)

2021-02-09 16:39 UTC, Derek-Hardy commented on src/client/java/teammates/client/scripts/ListActiveInstructors.java
> +        ArrayList<String> activeInstructorEmails = new ArrayList<>();
I think `Set` would be a more appropriate data structure for `contains` and `add` operations?

2021-02-10 09:43 UTC, Derek-Hardy approved these changes
LGTM

2021-02-10 16:53 UTC, damithc commented
I gave it a try. Took 22 minutes to finish, and produced 1.6k results. So, the approach is not very scalable.  It might even time out when we have even more sessions. We have 66K sessions by the way.
If the sessions are given to us in the order they were created, perhaps we can terminate after we hit a session that's outside of the period?

2021-02-10 17:20 UTC, daongochieu2810 commented
> I gave it a try. Took 22 minutes to finish, and produced 1.6k results. So, the approach is not very scalable. It might even time out when we have even more sessions. We have 66K sessions by the way.
> If the sessions are given to us in the order they were created, perhaps we can terminate after we hit a session that's outside of the period?

got it, I will try to prune it as you suggested

2021-02-13 00:30 UTC, rrtheonlyone commented
You do not need to binary search after fetching ALL sessions. 

I believe you can do this with just one query that can filter by created time - like this (just an arbitrary example):

```java
ofy().load().type(CourseStudent.class)
                   .filter("createdAt >", queryEntitiesFrom)
                   .filter("createdAt <=", queryEntitiesTo)
```                    

Furthermore, since the `creatorEmail` is indexed, you can then do a projection on the query to retrieve it - `project()`.

It will look something like - `ofy.load().type(..).filter(..).filter(..).project(..)`

This will allow you to do just one query to fetch everything you need. This should be much faster as the database will help optimize for you.

2021-02-14 03:55 UTC, rrtheonlyone requested changes
Minor Change - do test the script locally before pushing in future :)

2021-02-14 03:55 UTC, rrtheonlyone commented on src/client/java/teammates/client/scripts/ListActiveInstructors.java
> +        ofy().load().type(FeedbackSession.class)
almost there, you have to use a field given in the class as a filter (and the field has to be indexed)

```java
ofy().load().type(FeedbackSession.class)
        .filter("startTime >=", startTime)
        .filter("startTime <=", endTime).project().forEach(feedbackSession -> {
            activeInstructorEmails.add(feedbackSession.getCreatorEmail());
        })
```

Let's use `startTime`

2021-02-14 12:25 UTC, rrtheonlyone approved these changes
Looks good - prof @damithc do see if this is faster when you have time.

This script finds the list of active instructors using the start time of the feedback sessions they have created. This is just a heuristic - I am not sure if we can find all active instructors using this.

2021-02-14 14:37 UTC, damithc commented
> Looks good - prof @damithc do see if this is faster when you have time.

This one takes about 4 minutes. Nice!

2021-02-15 02:09 UTC, merged