[#10959] Paginate frontend call to webapi for large course
TEAMMATES/teammates pull request #10960
Opened 2021-02-13 15:53 UTC by moziliar

Part of #10959

**Outline of Solution**

Break down result download to per question level. Might need to experiment with the threshold to make granular download for smaller courses (OOM issue?)

From the current experiment, since the responses per question fetched are in different servlet, the memory pressure is minimal, possibly due to that GC can safely reclaim the servlet memory. This is better for even smaller courses that might result in memory spike for download (observed for a decently sized course where the memory shot up to close to the maximum)

2021-02-15 20:16 UTC, teikjun commented
I didn't notice this earlier, but the "Download Results" button can be accessed from the "Home" and "Sessions" tab via the session table as well. When accessed this way, the download is not processed in batches, so it may TLE like before. I'm still trying to resolve this, I'll merge it together with the frontend changes later. 

![image](https://user-images.githubusercontent.com/46853051/107984914-fd312000-7003-11eb-8a7b-109aa0fb345b.png)

At the moment, `instructor-session-base-page` doesn't load any question-related information. We'll need to load all the `feedbackQuestionId` (at least), in order to break down the download to question-level. I believe there will be a slight overhead for page loading speed, but I couldn't think of any better solution 😅 

On the UI side, the progress bar is positioned on top of the modal, so it displays correctly on both pages.

2021-02-18 15:57 UTC, moziliar commented
@teikjun Sorry that this PR did not tackle that issue... 
I believe solution 1 is more probable. So the rationale for this is that the workflow either consists of
* instructor click download result from session base -> FE fetches all questionIds -> FE downloads with paginated calls
* instructor click view result -> FE fetches all questionIds (and the rest...) -> instructor click download results -> FE downloads with paginated calls
Comparing the above, the former seems more probable as a smoother workflow without additional overhead (or less) in latency. I would encourage that.

2021-02-26 07:06 UTC, hcwong approved these changes
👍 LGTM. The features worked for me - tested with 300 users. Flame graphs and waterfall diagrams were also very helpful. 

However, I did notice that at when there are many students, and we try to load the responses to a question in teammates, it takes quite a while. Perhaps this can also be fixed in another PR.
<img width="1306" alt="laggy question fetching" src="https://user-images.githubusercontent.com/28432397/109267119-08761e00-7844-11eb-8c14-6ab55215f24b.png">

2021-02-26 07:13 UTC, moziliar commented
@hcwong Thank you for your review. I figured that improving the performance might incur operational cost. We could by all means parallelise the workflow (pagination again with `forkJoin` or backend forkJoin), but would increase memory consumption and thus instance count. Not sure if the cost is justified.

@damithc prof, any idea if we should give a better UX for this workflow at a cost?

2021-02-26 08:25 UTC, damithc commented
> @damithc prof, any idea if we should give a better UX for this workflow at a cost?

Provided the load operation will not time out, perhaps simply show a message below the spinner cautioning the user that this particular question will take a long time to load?

2021-02-26 08:36 UTC, moziliar commented
@damithc looks like a good first issue idea. Will just create a ticket? Low priority given no complaints made from the instructors yet.

2021-02-27 07:16 UTC, rrtheonlyone commented
Yes that is a good spot @hcwong - let's perhaps create an issue for this and have a separate discussion on this there @moziliar. This PR is more about improving the downloads results feature.

2021-02-27 08:10 UTC, rrtheonlyone requested changes
Awesome work 💯 - I think this PR does a pretty good job of fixing the issues faced in the past when downloading session results for large courses. 

The change is pretty small since we are just leveraging on existing functionality. Good to see some stress testing done above. 

Regarding the user experience:
- We should abort the progress bar automatically upon failure. Right now the progress bar just freezes and we see a toast. 
- There is an empty file committed in the PR (please remove that)
- When we click somewhere on the screen right now, the progress bar disappears but the download still continues to take place - we should not close progress bar modal if user clicks outside.

2021-02-27 08:10 UTC, rrtheonlyone commented on src/web/services/simple-modal.service.ts
> +  openDownloadModal(header: string, type: SimpleModalType,
Maybe rephrase this to `openLoadingModal`? Since this is a generic service that can be reused for other functions.

2021-02-27 14:09 UTC, teikjun commented
Thanks for the reviews! The requested changes have been made in https://github.com/moziliar/teammates/pull/23, and will be merged into this main PR soon. I have two concerns:

#### 1. Clicking outside the screen:
The progress bar isn't supposed to disappear when user clicks outside the screen - there is a transparent overlay (behind the loading modal and in front of the content) that is intended to prevent that. I'm not able to reproduce the bug so far on Chrome/Firefox. Can I ask what browser are you using? I'll try to investigate this bug further.

#### 2. Empty files:
I noticed that there are multiple empty `.scss` files in the codebase. Should I open another issue/PR to remove the rest of them?

2021-02-27 15:47 UTC, rrtheonlyone commented
I am using chrome version `88.0.4324.192 (Official Build) (x86_64)` on macOS. I just tried and it seems I can click outside and close the modal:

![captured_TM](https://user-images.githubusercontent.com/10579415/109392239-02706200-7956-11eb-8db0-2bc1902c154a.gif)

Regarding empty files, small issue - I think can leave it then.

2021-02-28 17:59 UTC, teikjun commented
Thanks @rrtheonlyone for the information! The bug has been resolved in moziliar#23. 
We'll review the changes internally and then request a final review from you.

2021-03-06 10:31 UTC, rrtheonlyone approved these changes
LGTM 💯 

UI looks good now! Just one minor thing.. @teikjun could you also abort the download when the 'X' button is pressed in the modal? Right now even after you press the 'X' - the download continues :P Once that is fixed, we can merge in.

2021-03-06 23:01 UTC, teikjun commented
The requested changes have been made in https://github.com/moziliar/teammates/pull/24. Good to go after getting approval from @moziliar 👍

2021-03-13 13:29 UTC, rrtheonlyone commented
Looks good :)

2021-03-13 13:32 UTC, merged