Add endpoint to fetch pagination metadata
TEAMMATES/teammates pull request #10962
Opened 2021-02-14 05:20 UTC by daongochieu2810

Part of #10959

Endpoint to fetch the total number of responses for a question in order to prepare pagination calls.
Path: ```/webapi/pagination/metadata```
Params: course ID, instructor email, question ID
Response: number of submitted responses, question ID

2021-02-14 06:27 UTC, moziliar requested changes
Maybe we should discuss the entire workflow, then look into the exact implementation details. This might be an expensive call that could create noise in monitoring.

2021-02-14 06:27 UTC, moziliar commented on src/main/java/teammates/common/util/Const.java
> +        public static final String PAGINATION_META_DATA = URI_PREFIX + "/pagination/metadata";
Does this endpoint have to reside in a separate routing group? If so, what other calls could there possibly be in the same `/pagination/` routing group?

2021-02-14 06:27 UTC, moziliar commented on src/main/java/teammates/logic/api/Logic.java
> +    public int getSubmittedResponseCountForQuestion(String questionId) {
I have some doubt over the granularity of the metadata fetch:
* Is per question response count really useful? (maybe one could just use the question result call to get all the response and count the length in an inexpensive way)
* I think you could actually make it course/session wide to improve the usefulness per call.

2021-02-14 06:27 UTC, moziliar commented on src/main/java/teammates/storage/api/FeedbackResponsesDb.java
> +                .filter("feedbackQuestionId =", questionId)
Can check if this filter reads into the document? And what cost will this bring?
Can use the mock script to populate some data and test the cost of this operation.

2021-02-14 06:27 UTC, moziliar commented on src/main/java/teammates/ui/webapi/GetPaginationMetaDataAction.java
> +    private static final String MESSAGE_NOT_INSTRUCTOR_ACCOUNT = "You did not login as an instructor,"
message doesn't seem to match the intent

2021-02-14 06:27 UTC, moziliar commented on src/main/java/teammates/ui/webapi/GetPaginationMetaDataAction.java
> +    private static final String MESSAGE_INSTRUCTOR_NOT_FOUND = "The instructor is not in the course you are given,"
ditto

2021-02-14 06:27 UTC, moziliar commented on src/main/java/teammates/ui/webapi/GetPaginationMetaDataAction.java
> +        int submittedResponseCount = logic.getSubmittedResponseCountForQuestion(feedbackQuestionId);
what happened if the question does not exist? This doesn't suggest any of those errors.

2021-03-13 14:34 UTC, rrtheonlyone commented
I think we can close this PR - are we planning on doing anything further with this? @daongochieu2810 @moziliar

2021-03-13 14:43 UTC, daongochieu2810 commented
I dont think we need to be really detailed on pagination, so yes we should close this PR

2021-03-13 14:43 UTC, closed without merging