[#10917] Fix unexpected behaviour when reverting to template feedback path
TEAMMATES/teammates pull request #10975
Opened 2021-02-21 21:35 UTC by stapletonce

Fixes #10917

**Outline of Solution**

In the changeGiverRecipientType on line 240 of /web/app/components/question-edit-form/question-edit-form.component.ts, I added an if statement that checks if a custom feedback path is currently being used the visibility settings will not change when it is reverted to its template settings.

https://user-images.githubusercontent.com/55817381/108639389-43eaa400-7462-11eb-939d-54c64c8f93f5.mov

2021-03-01 04:13 UTC, Derek-Hardy reviewed
@stapletonce One of the related e2e test has failed. It will be worthwhile to investigate whether to update e2e test workflow accordingly with latest change or to fix potential loophole in the current implementation.

It will be helpful to look into relevant parts of `InstructorFeedbackEditPageE2ETest.java` for debugging.

2021-03-15 19:30 UTC, stapletonce commented
@Derek-Hardy Hello! I believe I have finished fixing this issue though I'm not sure if I have access to get the ongoing label off.

2021-03-20 23:35 UTC, stapletonce commented
@madanalogy, @Derek-Hardy, @damithc This issue is no longer in progress and is ready for review (as far as I can tell!)

2021-03-23 17:00 UTC, moziliar requested changes
Sorry for the late review. I roughly get the problem and your solution which fixes the issue of `isUsingOtherFeedbackPath` not being updated to true in this workflow. Can you help to address some of my doubts above?

2021-03-23 17:00 UTC, moziliar commented on src/web/app/components/question-edit-form/question-edit-form.component.ts
> +        this.model.giverType === giverType && this.model.recipientType === newRecipientType) {
Can I check with you if all the conditions here are necessary? E.g. checking `this.isCustomFeedbackVisibilitySettingAllowed`

2021-03-23 17:00 UTC, moziliar commented on src/web/app/components/question-edit-form/question-edit-form.component.ts
> +        recipientType: newRecipientType,
Do you need to trigger an update of `recipientType` if it already is `newRecipientType` by the condition above? Likewise for `giverType`.
The update here following the equality checks seems redundant.

2021-03-23 21:07 UTC, stapletonce commented
@moziliar I agree, both of those areas seem redundant to me. I have updated the code and re-performed the tests with those changes.

2021-03-28 12:39 UTC, moziliar commented
Can I check what would happen if the user clicks `custom feedback path` again in the dropdown when the ui is already in `custom feedback path`? Logically, this code looks to me that it would just toggle the template back to default?

2021-03-30 19:53 UTC, stapletonce commented
https://user-images.githubusercontent.com/55817381/113047982-01f30300-9170-11eb-8305-798a079fd3cb.mov

It does not toggle back to default with these changes @moziliar

2021-03-31 05:27 UTC, moziliar commented
Yup, tested locally and the change seems to solve the problem partially.

Can you help to look into this problem too?
![Mar-31-2021 13-26-41](https://user-images.githubusercontent.com/19870898/113094711-c23a2300-9224-11eb-8d89-2e51eb4bc387.gif)

2021-03-31 16:27 UTC, stapletonce commented
@moziliar What is the desired behavior here? I was under the impression that the visibility should only stay the same when switching between custom and template when the custom and template matched. In your example, you switch from Students in this course -> Giver (Self feedback) to Students in this course -> Giver's teammates so visibility resets.

2021-03-31 16:33 UTC, moziliar commented
@stapletonce Sorry I didn't specify what I sense wrong: notice how the first time I click to Giver's teammates template for the first time, the custom template part still stays, whereas the second time triggers the revert to the template display. The behaviour seems correct for people who are involve in fixing it, but might be confusing to new instructor has not much visual change has been rendered for the first click (the second is a lot more drastic than the first).

Maybe we could just make them the same as discussed in the issue:

> User interface reverts to template display prior to selecting custom feedback path

2021-03-31 16:41 UTC, stapletonce commented
@moziliar Ah, I see. Thank you for clearing this up - I can work on this now!

2021-04-05 17:17 UTC, moziliar commented
@stapletonce hi, is this PR ready for review?

2021-04-05 17:18 UTC, stapletonce commented
yes please!

> On Apr 5, 2021, at 1:17 PM, Mo Zongran ***@***.***> wrote:
> 
> 
> @stapletonce <https://github.com/stapletonce> hi, is this PR ready for review?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/TEAMMATES/teammates/pull/10975#issuecomment-813514256>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ANJ3JJKR46XUH24ITOTMC43THHWCPANCNFSM4X7MQBXA>.
>

2021-04-05 17:23 UTC, moziliar requested changes
One minor part. The rest look ok!

2021-04-05 17:23 UTC, moziliar commented on src/web/app/components/question-edit-form/question-edit-form.component.ts
> +      if (this.model.isUsingOtherFeedbackPath) {
It is perhaps not a good practice to have two such if's as they create an arrow-antipattern. You might want to just do 
```suggestion
    if (this.model.giverType === giverType && this.model.recipientType === newRecipientType
      && this.model.isUsingOtherFeedbackPath) {
```
in which the precedence of the booleans achieves the exact same effect.

2021-04-05 17:37 UTC, moziliar commented
Sorry I take that back... it seems like the logic is wrong in this case🥲 you can revert that and the rest LGTM

2021-04-05 17:38 UTC, moziliar commented on src/web/app/components/question-edit-form/question-edit-form.component.ts
> +      if (this.model.isUsingOtherFeedbackPath) {
Wrong logic here. Shouldn't omit the path where the function does nothing

2021-04-05 18:05 UTC, moziliar approved these changes
LGTM. Wait for CI to complete

2021-04-05 18:17 UTC, stapletonce commented
@moziliar success 🎉

2021-04-06 16:06 UTC, stapletonce commented
@Derek-Hardy ready for review

2021-04-08 13:58 UTC, Derek-Hardy approved these changes
LGTM, thanks for the contribution.

2021-04-12 11:00 UTC, madanalogy approved these changes

2021-04-12 14:12 UTC, merged