[#10938] Support copying courses
TEAMMATES/teammates pull request #11012
Opened 2021-03-05 18:46 UTC by LeeBadal

Part of  #10938 

**Outline of Solution**
* Implements a copy course option for course instructors in the same fashion as copy sessions
* Includes an option to chose specific sessions
* Includes basic front end tests.
NOTE: Is missing E2E tests, did not manage to implement tests that passed reliably. Most likely need assistance if this would be requested.

Screenshots of use case below:
![Screenshot from 2021-03-05 18-55-11](https://user-images.githubusercontent.com/43146567/110158062-35e53d80-7de9-11eb-8db6-052e545e511b.png)
![Screenshot from 2021-03-05 19-00-07](https://user-images.githubusercontent.com/43146567/110158076-3978c480-7de9-11eb-8f15-d29c50b5f17e.png)
![Screenshot from 2021-03-05 19-01-12](https://user-images.githubusercontent.com/43146567/110158089-3d0c4b80-7de9-11eb-849b-2391c381bdd9.png)

2021-03-06 03:24 UTC, damithc commented
Some suggestions for the modal dialog:
* Title need to contain 'and its sessions'. It's implied.
* Also show which course (id, name) is being copied
* Also allow specifying name and timezone ? Possibly reuse the code from 'create new course' feature?
* If you use a table for the session list, you can use a tick box in the top row for 'select/unselect all' behavior, which is more common UX pattern these days
* Avoid the word 'Choose' as it hints of a choice between options

2021-03-06 15:21 UTC, Derek-Hardy commented
@LeeBadal Lint tests are failing, which suggests some of your coding style do not conform with the project standard. Try to run `./gradlew lint` or `npm run lint` to inspect and fix them.

2021-03-08 12:30 UTC, Olle251 commented
The coding style is fixed.

The modal for copying a course is now updated to look like this:

<img width="929" alt="Screenshot 2021-03-08 at 13 18 39" src="https://user-images.githubusercontent.com/37701987/110320825-2cd6b500-8011-11eb-8d92-825d253e76bd.png">

We did this as an assignment in school and we hope our solution is useful for this project. 

We will probably not have time to fix more on this issue, so if there is more to be fixed someone else is welcome to take over from here.

2021-03-08 12:59 UTC, damithc commented
Good progress!
Here's an example of how to use a 'select all' checkbox
![image](https://user-images.githubusercontent.com/1673303/110324131-89a59000-8050-11eb-8ae5-a7292d9ce3c5.png)

It doesn't need a label if you place is appropriately.

If not using a table, perhaps you can try something like this?

> [  ] **Sessions to copy:**
> [  ] session 1
> [  ] session 2

2021-03-09 18:32 UTC, Olle251 commented
Changed it to look like this now:

<img width="724" alt="Screenshot 2021-03-09 at 19 31 26" src="https://user-images.githubusercontent.com/37701987/110519879-20845200-810e-11eb-9b82-792aa1076a19.png">

2021-03-10 03:25 UTC, damithc commented
> Changed it to look like this now:
> 
> <img alt="Screenshot 2021-03-09 at 19 31 26" width="724" src="https://user-images.githubusercontent.com/37701987/110519879-20845200-810e-11eb-9b82-792aa1076a19.png">

Nice. UI looks OK to me now, but that's just me. Feedback from others welcome.

2021-03-10 03:31 UTC, damithc commented
> UI looks OK to me now, but that's just me. Feedback from others welcome.

Actually, you can consider something like this:

> ### Copy course
> ----
> **Copy from**: [SE101-2021] Software Engineering
>
> **New course**:
> Course ID: [   ]
> Course name: [  ]
> Timezone: [  ]
> ...

2021-03-10 11:56 UTC, Olle251 commented
OK, now it looks like this:
<img width="724" alt="Screenshot 2021-03-10 at 12 13 49" src="https://user-images.githubusercontent.com/37701987/110625478-c2a04a80-819f-11eb-9afa-0007ab73ceb3.png">

2021-03-10 12:05 UTC, damithc commented
> OK, now it looks like this:
> <img alt="Screenshot 2021-03-10 at 12 13 49" width="724" src="https://user-images.githubusercontent.com/37701987/110625478-c2a04a80-819f-11eb-9afa-0007ab73ceb3.png">

👍

2021-04-11 17:36 UTC, daongochieu2810 requested changes

2021-04-11 17:36 UTC, daongochieu2810 commented on src/web/app/components/copy-course-modal/copy-course-modal.component.ts
> +const formatTwoDigits: Function = (n: number): string => {
With ES2017, we can do 
`const zeroPad = (num, places) => String(num).padStart(2, '0')`
[source](https://stackoverflow.com/questions/2998784/how-to-output-numbers-with-leading-zeros-in-javascript)

2021-04-11 17:36 UTC, daongochieu2810 commented on src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
> +      modalRef.componentInstance.newCourseId = courseId;
Lets separate these inits into a helper function

2021-04-11 17:36 UTC, daongochieu2810 commented on src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
> +  Courses, FeedbackQuestion, FeedbackQuestions, FeedbackSession, FeedbackSessions,
I think we should have consistent newlines

2021-04-11 17:36 UTC, daongochieu2810 commented on src/web/app/components/copy-course-modal/copy-course-modal.component.ts
> +  timezones: Timezone[] = [];
Its probably better to group these attributes into a type e.g CopyCourseModalAttributes

2021-05-16 05:27 UTC, damithc commented
@LeeBadal any plans to continue this PR? It would be a pity to throw away all the good work you've done.

2021-06-13 04:05 UTC, damithc commented
Closing this as the work is continued in #11168

2021-06-13 04:05 UTC, closed without merging