[#10481] Remove video tour on home page
TEAMMATES/teammates pull request #11140
Opened 2021-05-21 10:23 UTC by hhdqirui

Fixes #10481

**Outline of Solution**
Remove `div` tag for video tour. Make the remaining button center.

2021-05-21 14:07 UTC, moziliar commented
Hi @hhdqirui , for ease of review, it is advised to attach screenshot to the PR, ideally before-after change.

2021-05-24 03:49 UTC, hhdqirui commented
> Hi @hhdqirui , for ease of review, it is advised to attach screenshot to the PR, ideally before-after change.

Hi. Thank you for the advice! Screenshots are attached in the PR description.

2021-05-24 11:20 UTC, moziliar commented
@damithc hi prof just checking if my intuition is ok 🤣 is it just me or the "centred" button is not so centred anymore with the peeled page at the bottom left?

2021-05-24 12:05 UTC, damithc commented
> @damithc hi prof just checking if my intuition is ok 🤣 is it just me or the "centred" button is not so centred anymore with the peeled page at the bottom left?

Doesn't make a big difference to my eye though.

2021-05-24 12:14 UTC, moziliar commented
@damithc thank you for your input.

I guess when you compare the above and below images, you could see that the button doesn't fall right in between the two buttons before the change. But if you are ok with that, so am I!

2021-05-24 12:18 UTC, moziliar requested changes
Code LGTM. A minor naming nit.

2021-05-24 12:18 UTC, moziliar commented on src/web/app/pages-static/index-page/index-page.component.scss
> +.center {
The class name is too generic. You could rename it to something like `.button-center` as different html tags require different ways to center, e.g. `.item-center`.

2021-05-27 10:34 UTC, hhdqirui commented
> @hhdqirui what do you think? I honestly think it could go a little left (is it my OCD acting now...)

Hi @moziliar, I have made some manual measurement. It is indeed at the center. Maybe the screenshots are a bit misleading.

2021-05-30 05:53 UTC, moziliar approved these changes
LGTM!

2021-05-30 08:46 UTC, rrtheonlyone approved these changes

2021-05-30 10:39 UTC, merged