[#11177] Create new user role senior developer
TEAMMATES/teammates pull request #11183
Opened 2021-06-08 06:23 UTC by hhdqirui

Fixes #11177

**Outline of Solution**
1) Modify `UserInfo.java` to have a `isDeveloper` Boolean field and getter methods for it.
2) Create a static list of `UserId` to “Developer” mapping for prod server instance. The config file that we choose to store this list can be `build.properties`. The format would be a comma separated list. For example: `app.seniorDeveloper.ids = id1000,id1001,id1002,id1003`. For getting this property and converting to a java list, we can use the `split` method.
3) In `teammates/common/util/Config.java`, add a `seniorDevelopers` field with type `List<String>` and methods to load this list from `build.properties`.
4) Add a new method `isUserSeniorDeveloper(String id)` in `UserProvision.java` to check whether the `id` given in the parameter is in the list of senior developer (`Config.seniorDevelopers`). This new method will be called in `getCurrentLoggedInUser()` and set `isDeveloper` of `userInfo` object accordingly.

2021-06-13 06:10 UTC, wkurniawan07 requested changes

2021-06-15 08:52 UTC, hhdqirui commented on src/main/java/teammates/logic/api/UserProvision.java
> +        userInfo.isSeniorDeveloper = this.isUserSeniorDeveloper(userInfo.getId());
OK. It is fixed.

2021-06-15 08:53 UTC, hhdqirui commented on src/main/java/teammates/logic/api/UserProvision.java
> +        return Config.SENIOR_DEVELOPERS.contains(id);
Thank you for the advice. I have removed the method.

2021-06-15 08:54 UTC, hhdqirui commented on src/main/resources/build.template.properties
> +app.seniorDeveloper.ids =
Thank you for the advice. It is fixed.

2021-06-15 08:54 UTC, hhdqirui commented on src/main/java/teammates/common/util/Config.java
> +        SENIOR_DEVELOPERS = Arrays.asList(properties.getProperty("app.seniorDeveloper.ids").split(","));
It is fixed.

2021-06-15 08:54 UTC, hhdqirui commented on src/main/java/teammates/common/util/Config.java
> +    public static final List<String> SENIOR_DEVELOPERS;
Fixed.

2021-06-15 08:57 UTC, hhdqirui commented on src/main/resources/build.template.properties
> +app.seniorDeveloper.ids =
Thank you for the advice. It is fixed. Do you also advice to change other variable and method names that contain `seniorDeveloper` to `seniorDev`?

2021-06-27 06:17 UTC, rrtheonlyone commented
@hhdqirui please also update the name to "maintainer" as discussed

2021-07-04 11:20 UTC, hhdqirui commented
@wkurniawan07 @rrtheonlyone Hi it is ready for review.

2021-07-10 17:07 UTC, wkurniawan07 requested changes
There are still mentions of "senior developers" in code.

2021-07-14 06:31 UTC, hhdqirui commented
It is all cleared now. No more "senior developer".

2021-07-15 15:58 UTC, wkurniawan07 approved these changes
LGTM

2021-07-15 16:05 UTC, merged