[#11175] Change most mentions of Datastore to database
TEAMMATES/teammates pull request #11261
Opened 2021-07-09 21:53 UTC by BoazWu

Fixes #11175

Not ready for review

2021-07-10 13:18 UTC, wkurniawan07 requested changes
Excellent job! Indeed these are the terms that should have been database instead of datastore. Just one minor change request.

2021-07-10 21:26 UTC, BoazWu commented on docs/design.md
> +- Hiding the complexities of the database from the `Logic` component. All GQL queries are to be contained inside the `Storage` component.
Thanks for the feedback! I made the change

2021-07-11 01:23 UTC, wkurniawan07 requested changes

2021-07-11 02:53 UTC, wkurniawan07 approved these changes

2021-07-11 02:53 UTC, wkurniawan07 commented on src/client/java/teammates/client/connector/DatastoreClient.java
> + * Enables access to any datastore (local/production).
This is unrelated change, but I'm willing to close one eye

2021-07-11 02:53 UTC, merged