11235 datetime picker fix
TEAMMATES/teammates pull request #11306
Opened 2021-07-25 08:51 UTC by ChanwooJung1

Fixes #11235

2021-07-27 16:08 UTC, daongochieu2810 requested changes
Changes look good!

2021-07-27 16:08 UTC, daongochieu2810 commented on src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.ts
> +  }
I dont think these util functions should be placed here. Lets move them to `src/web/app/components/datepicker/datepicker.component.ts` or create a new module called `date-utils` to handle datetime operations

2021-07-29 08:38 UTC, halfwhole reviewed
It looks like the current approach relies on disabling search if the date is out of range, but perhaps we could restrict the date picker more directly?

https://github.com/TEAMMATES/teammates/blob/69ae1cc91e6d5d8b39a91be88022f80618f8f39a/src/web/app/pages-instructor/instructor-audit-logs-page/instructor-audit-logs-page.component.html#L57

There's a `minDate` option in this line that could be changed to say `formModel.logsDateFrom`, would this solve our needs?

2021-08-14 09:55 UTC, hhdqirui commented
@ChanwooJung1 for your kind update on the above.

2021-08-22 16:26 UTC, halfwhole commented
@ChanwooJung1 a kind reminder on this PR! please do tell us how you wish to proceed, thanks

2021-09-06 15:24 UTC, damithc commented
Guys, This PR seems to be stalling (no activities for the past 7 days). :snail: :cry:
Hope someone can get it to move forward again soon...

2021-09-07 14:23 UTC, daongochieu2810 commented
@ChanwooJung1 any update? If not we might have to close this PR and let other people take on the issue

2021-09-15 14:21 UTC, moziliar commented
Close due to inactivity and open the issue up for other first-timers. Feel free to reopen and start contributing if there isn't already an active contributor for the issue!

2021-09-15 14:21 UTC, closed without merging