[#11433] Add option for removing unregistered instructors
TEAMMATES/teammates pull request #11460
Opened 2021-10-31 20:01 UTC by tjtanjin

Fixes #11433 

**Outline of Solution**

- Provide a button to delete unregistered instructors when they turn up in search results.
- If the delete button is pressed, a prompt first pops up to ask for confirmation.
- Upon confirmation of delete, the instructor and its associated demo course/students will be deleted (through a new API call).
- The deleted rows are then removed from the search table results.

Example usage (bob1 is registered while bob2 is unregistered):
https://user-images.githubusercontent.com/43908963/139599454-bfeddd24-2f51-4ec4-a272-93690e989e48.mov

2021-11-03 10:28 UTC, wkurniawan07 requested changes
I find it hard to justify proceeding here because:
- This is a very dangerous implementation, as you're conflating unregistered instructor who requested account (target audience of this feature) and general unregistered instructor (actual audience as of the current implementation).
- There shouldn't be a need to implement a new endpoint, as we only need to delete the demo course (`DELETE /course`). The difficulty comes in determining whether the target instructor is a demo instructor that has not legitimately used the system.
- #11396 will make this implementation obsolete.

2021-11-03 10:28 UTC, wkurniawan07 commented on src/main/java/teammates/logic/api/Logic.java
> +     * Deletes an unregistered instructor cascade its associated demo course and students.
I don't think a part of the code that checks whether the course/instructor is only demo exists.

2021-11-03 15:58 UTC, jianhandev commented
@tjtanjin reminder on this PR, some tests are failing.

2021-11-03 21:27 UTC, tjtanjin commented
> I find it hard to justify proceeding here because:
> 
> * This is a very dangerous implementation, as you're conflating unregistered instructor who requested account (target audience of this feature) and general unregistered instructor (actual audience as of the current implementation).
> * There shouldn't be a need to implement a new endpoint, as we only need to delete the demo course (`DELETE /course`). The difficulty comes in determining whether the target instructor is a demo instructor that has not legitimately used the system.
> * #11396 will make this implementation obsolete.

Hello and thank you for the feedback! May I clarify what is the distinction between an unregistered instructor who requested account and a general unregistered instructor? I am under the impression that in both instances, there are no courses attached to them and that it is logically sound to delete them.

2021-11-04 04:50 UTC, wkurniawan07 commented
You're making use presence of `instructor.googleId` to determine whether an instructor is unregistered or not, which is valid. However you seem to forget that not all unregistered instructors are new instructors who requested accounts; they might very well be other instructors added to a course by the course owner.

2021-11-05 03:34 UTC, tjtanjin commented
Okie so to be sure that I am understanding this correctly, there is currently no way to distinguish the 2 groups of unregistered instructors. However, this distinction is necessary so that the admin will not delete the group of unregistered instructors who were added by a course owner?

2021-12-13 16:05 UTC, jianhandev commented
@wkurniawan07 since #11396 is still in progress, shall we put this PR on hold first?

2022-03-11 02:41 UTC, samuelfangjw commented
Superseded by #11582

2022-03-11 02:41 UTC, closed without merging