[#11492] Support configuring separate front-end URL for E2E testing
TEAMMATES/teammates pull request #11523
Opened 2022-01-14 08:39 UTC by shadowezz

Fixes #11492 

**Outline of Solution**

Allow separate configuration of frontend and backend url for E2E testing in `test.properties`. All url navigations uses frontend url but logging out uses backend url.

2022-01-14 16:52 UTC, wkurniawan07 requested changes
Good work! There is just one place that is not correctly changed

2022-01-15 02:55 UTC, shadowezz commented on src/e2e/java/teammates/e2e/util/TestProperties.java
> +        return TEAMMATES_BACKEND_URL.matches("^https?://localhost:[0-9]+(/.*)?");
ok i see

2022-01-15 02:56 UTC, shadowezz commented on src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java
> +        String url = createFrontendUrl(Const.ResourceURIs.EXCEPTION)
I have made the changes. Just curious what is a resourceUri? Is it the same as an api endpoint?

2022-01-15 03:43 UTC, wkurniawan07 commented on src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java
> +        String url = createFrontendUrl(Const.ResourceURIs.EXCEPTION)
That is one way to look at it. RESTful APIs are designed around resources, e.g. `GET /course`, `POST /course`, `DELETE /course` are designed with course as the resource.

2022-01-15 04:31 UTC, shadowezz commented on src/e2e/java/teammates/e2e/cases/SystemErrorEmailReportE2ETest.java
> +        String url = createFrontendUrl(Const.ResourceURIs.EXCEPTION)
ah ok

2022-01-15 04:42 UTC, wkurniawan07 approved these changes
LGTM, thanks for contributing!

2022-01-15 04:42 UTC, merged