[#8787] New instructors: set the time zone of the sample course to match user
TEAMMATES/teammates pull request #11557
Opened 2022-02-06 11:50 UTC by samuelfangjw

Fixes #8787 

**Outline of Solution**

1. In `account.service.ts`, `createAccount()` has a new parameter `timezone`.
2. When a user creates an account, timezone is passed to as an argument to `createAccount()`. The timezone is guessed from the user's web browser settings. Timezone is sent as part of the post request.
3. In `CreateAccountAction`, when creating demo course, timezone in the template is replaced by the user's timezone. If timezone if invalid, default timezone is used instead.

2022-02-06 12:31 UTC, wkurniawan07 commented
Quoting myself from https://github.com/TEAMMATES/teammates/pull/11243#issuecomment-898993617:
> In case you're not aware, the sessions of the sample course are set to have end time at 11.59pm in a preset timezone. Moving the timezone without also moving those end times will make it really weird, e.g. "why is this sample session ending at 4am?".

2022-02-06 12:38 UTC, samuelfangjw commented
> Quoting myself from [#11243 (comment)](https://github.com/TEAMMATES/teammates/pull/11243#issuecomment-898993617):
> 
> > In case you're not aware, the sessions of the sample course are set to have end time at 11.59pm in a preset timezone. Moving the timezone without also moving those end times will make it really weird, e.g. "why is this sample session ending at 4am?".

oh right, will update.

2022-02-10 04:22 UTC, NicolasCwy requested changes
Mostly nits, but also should `InstructorSampleData.json` have a working default state, commented directly on that section!

2022-02-10 04:24 UTC, samuelfangjw commented on src/main/resources/InstructorSampleData.json
> +      "timeZone": "demo.timezone"
Thanks for spotting this

2022-02-10 04:53 UTC, samuelfangjw commented
@NicolasCwy Made the suggested changes! Also added a check in `CreateAccountAction#importDemoData()` - if timezone is default timezone (UTC), no need to replace timezone specific data. Could you take another look to see if it's ok?

2022-02-10 05:21 UTC, NicolasCwy approved these changes
LGTM!

2022-02-12 08:18 UTC, wkurniawan07 approved these changes

2022-02-13 08:47 UTC, merged