[#11086] Enrolling students: show a progress indicator when enrolling a large class
TEAMMATES/teammates pull request #11600
Opened 2022-02-26 06:35 UTC by FergusMok

Fixes #11086 

Added a progress bar to the student enrollment. 

Example with 225 students for enrollment: 
https://user-images.githubusercontent.com/10182564/155832625-dd2e993a-7260-4152-bfd2-7c2a5986306f.mp4

2022-02-28 13:00 UTC, ziqing26 approved these changes
LGTM!

2022-03-06 16:44 UTC, moziliar commented
Reminder to resolve the conflicts!

2022-03-10 05:58 UTC, NicolasCwy approved these changes
LGTM!

2022-03-10 05:58 UTC, NicolasCwy approved these changes
LGTM!

2022-03-26 16:25 UTC, wkurniawan07 requested changes

2022-03-26 16:25 UTC, wkurniawan07 commented on src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.ts
> -    })).subscribe({
Unrelated change here. The only change that should be observed here is the addition of `this.progressBarService.updateProgress(0);`.

2022-03-26 16:25 UTC, wkurniawan07 commented on src/web/app/pages-instructor/instructor-course-enroll-page/instructor-course-enroll-page.component.html
> +                    <tm-ajax-loading *ngIf="isEnrolling"></tm-ajax-loading>
Unrelated change and inconsistent indentation (compare with the `Enroll students` line after this)

2022-03-27 11:54 UTC, wkurniawan07 approved these changes

2022-03-27 11:54 UTC, merged