[#10920] Add front-end unit tests for FeedbackResponsesService
TEAMMATES/teammates pull request #11629
Opened 2022-03-06 12:47 UTC by jayasting98

Part of #10920 

**Outline of Solution**

Front-end unit tests were added for each method in `FeedbackResponsesService`.

2022-03-08 07:32 UTC, jianhandev commented
@AdithyaNarayan appreciate your review on this PR!

2022-03-14 06:38 UTC, AdithyaNarayan requested changes

2022-03-14 06:38 UTC, AdithyaNarayan commented on src/web/services/feedback-responses.service.spec.ts
> +  });
Only the parameters seem to be different across all these test cases. Why not use a `Record`/List to store pairs of `QuestionType` and Response details and then loop through them? Or add them in the same test case?

2022-03-14 06:38 UTC, AdithyaNarayan commented on src/web/services/feedback-responses.service.spec.ts
> +    expect(service.isFeedbackResponseDetailsEmpty(feedbackQuestionType, feedbackResponseDetails))
A lot of duplicate code here too

2022-03-31 04:09 UTC, ypinhsuan commented
Hi @jayasting98, any updates on this PR?

2022-03-31 08:07 UTC, jayasting98 commented
@ypinhsuan Sorry, I have been a bit busy. Let me see if I can try to do it next week.

2022-04-13 10:57 UTC, jayasting98 commented
@AdithyaNarayan @ypinhsuan Sorry it took a while; I was busy. I'm done now.

2022-04-15 16:27 UTC, AdithyaNarayan approved these changes
LGTM

2022-04-17 12:43 UTC, ypinhsuan approved these changes
Looks good!

2022-04-20 03:46 UTC, wkurniawan07 requested changes

2022-04-20 03:46 UTC, wkurniawan07 commented on src/web/services/feedback-responses.service.spec.ts
> +      questionid: '[auto-generated Datastore ID]',
Don't make any mention to "Datastore" or anything DB-related here. Even 'dummy question id' is sufficient.

2022-04-20 03:46 UTC, wkurniawan07 commented on src/web/services/feedback-responses.service.spec.ts
> +      key: '[generated registration key]',
No need to mention "generated" either. Front-end doesn't care how the values are created at the back-end.

2022-04-20 10:37 UTC, wkurniawan07 approved these changes

2022-04-20 12:22 UTC, merged