[#11572] Notification feature - Admin page update (edit) feature
TEAMMATES/teammates pull request #11663
Opened 2022-03-20 15:23 UTC by fsgmhoward

Part of #11572

This PR consists of code for the pages enabling the admin to update a notification. Since notification is rather simple and there is nothing linked to it to be edited together unlike feedback sessions, the same edit form (the one for creating notifications) will be reused.

Other improvements related to this is also included, including the removal of redundant code such as `isEditable` 

This PR is still WIP.

- [X] Frontend page for updating notification
- [ ] Frontend logic to PUT data to server
- [ ] Final check after PUT route backend API has been merged

2022-03-30 07:55 UTC, fsgmhoward commented
This is the preview of the feature:

![Preview](https://user-images.githubusercontent.com/10681776/160779923-c005fd27-dd2a-475e-a474-292b79ba0e64.gif)

Basically update and create share the same form. When in update mode, there will be minor differences such as "Shown Status" will be shown and button also changes to "Edit Existing Notification" (top left) and submit button becomes "save changes".

Also, as they share the same form, I change how the form close behaves. When the form is closed (by clicking the X at the top right corner), it will show a warning of losing data. It no longer retains form data when closing before saving (for both create and update).

![image](https://user-images.githubusercontent.com/10681776/160780721-c7808215-f26b-4fa9-b4a1-1c91e7529e45.png)

Then, when the admin has an existing edit form opened but clicks the "Edit" button of the other notification, it will also show the admin a similar warning:

![image](https://user-images.githubusercontent.com/10681776/160780897-2b5b0b54-cf7d-4b85-9c06-44db7c9a3ea0.png)

2022-03-30 11:26 UTC, zhaojj2209 requested changes
One quick edit needed as the notification end time is currently loaded incorrectly in the edit form, other than that LGTM!

2022-03-30 11:26 UTC, zhaojj2209 commented on src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.ts
> +    const endTime = moment(notification.startTimestamp);
```suggestion
    const endTime = moment(notification.endTimestamp);
```

2022-03-30 15:12 UTC, ziqing26 approved these changes
LGTM!

2022-03-31 03:32 UTC, NicolasCwy requested changes
LGTM just one nit, on deprecated style classes

2022-03-31 03:32 UTC, NicolasCwy commented on src/web/app/pages-admin/admin-notifications-page/notification-edit-form/notification-edit-form.component.scss
> +.notification-form-buttons > button {
I believe this can be deleted since you deleted the the row `notification-edit-form.component.html`(line 8)

2022-03-31 14:53 UTC, jianhandev approved these changes
Apart from the issue mentioned by @NicolasCwy above, LGTM.

2022-04-01 03:41 UTC, NicolasCwy commented on src/web/app/pages-admin/admin-notifications-page/admin-notifications-page.component.html
>    ></tm-notification-edit-form>
Just noticed this, could you put the right angled bracket on the previous line to close the component

2022-04-01 04:42 UTC, NicolasCwy approved these changes
LGTM

2022-04-01 05:56 UTC, t-cheepeng approved these changes
LGTM

2022-04-01 06:12 UTC, merged