[2488] Instructor: edit questions: give more recipient type options
TEAMMATES/teammates pull request #11815
Opened 2022-05-24 04:46 UTC by xyliew25

Fixes #2488

**Outline of Solution**

As suggested, 
1. For feedback path, modify the code such that the previously unused `STUDENTS_EXCLUDING_SELF` enum indicates exactly what it is named, but keep `STUDENTS` similarly defined.
2. Write and run a data migration script to migrate all `STUDENTS` to `STUDENTS_EXCLUDING_SELF`.
3. Remove the code that interprets `STUDENTS` as "students excluding self".

2022-05-24 04:52 UTC, xyliew25 commented
As of now, I have attempted Step 1 and 2.

Also, I understand that Issue [#2448](https://github.com/TEAMMATES/teammates/issues/2488) targets `TEAMS` as well, but I would like to get the `STUDENTS` part reviewed and finalized first before attempting the `TEAMS` part, as I believe similar implementation applies.

2022-05-24 04:58 UTC, wkurniawan07 commented
> As of now, I have attempted Step 1 and 2.

You cannot do step 3 now anyway; not until this set of change has been merged and the script run in the production DB.

2022-05-24 05:01 UTC, wkurniawan07 reviewed
Implementation is sufficient. Remember to update the script and the backend logic to also involve `TEAMS_INCLUDING_SELF`.

2022-05-24 05:07 UTC, xyliew25 commented on src/web/services/feedback-questions.service.ts
> +            FeedbackParticipantType.INSTRUCTORS, FeedbackParticipantType.TEAMS_EXCLUDING_SELF,
Ah yes, will do.

2022-05-24 06:38 UTC, xyliew25 commented
> Implementation is sufficient. Remember to update the script and the backend logic to also involve `TEAMS_INCLUDING_SELF`.

Oh wait, not sure if I got the wrong idea, but did you mean `TEAMS_EXCLUDING_SELF`?

2022-05-24 08:02 UTC, wkurniawan07 requested changes

2022-05-24 15:13 UTC, xyliew25 commented on src/client/java/teammates/client/scripts/DataMigrationForStudentsAndTeamsRecipientType.java
> +                .filter("recipientType =", null);
I overlooked it, my bad.

2022-05-26 17:13 UTC, wkurniawan07 requested changes

2022-05-26 17:13 UTC, wkurniawan07 commented on src/web/app/pages-instructor/instructor-session-edit-page/__snapshots__/instructor-session-edit-page.component.spec.ts.snap
> +                     The maximum number of students_excluding_self each respondent should give feedback to:
This unfortunately is no longer user-friendly. If previously we can just lowercase (I assume), we may either need a dedicated pipe here, or maybe just trimming the `_EXCLUDING_SELF` at the end.

2022-05-26 17:13 UTC, wkurniawan07 commented on src/main/java/teammates/common/datatransfer/FeedbackParticipantType.java
> +    TEAMS_EXCLUDING_SELF(false, true, true),
I don't think the third boolean should be `true`

2022-05-27 13:29 UTC, xyliew25 commented on src/web/app/components/teammates-common/feedback-path.pipe.ts
> +  transform(type: FeedbackParticipantType): any {
Ah yes, what about the existing `GiverTypeDescriptionPipe` and `RecipientTypeDescriptionPipe`? Their return types are also `any`. Should I change them as well, or leave them?

2022-05-27 13:34 UTC, wkurniawan07 commented on src/web/app/components/teammates-common/feedback-path.pipe.ts
> +  transform(type: FeedbackParticipantType): any {
Leave them, they are irrelevant for this issue/PR

2022-05-27 16:40 UTC, samuelfangjw approved these changes
LGTM! Great work on this :)

2022-05-27 17:42 UTC, merged