[#11825] Warn user before deleting last course
TEAMMATES/teammates pull request #11874
Opened 2022-06-23 11:30 UTC by inifnite

Fixes #11825

**PR Checklist**

**Outline of Solution**
An instructor can only lose access when the courses are deleted permanently. So, in the "instructor-courses-page.component.ts" , I checked if the course being deleted permanently is the last course in that institute or overall and showed the warning accordingly.

2022-06-23 15:25 UTC, zhaojj2209 requested changes
The current implementation causes both a warning toast and a warning modal to pop up when the user tries to delete the last course permanently; I believe a better solution would be to add the warning message in the existing modal, with more emphasis placed (e.g. bolding the text, changing text colour to red) if needed.

![image](https://user-images.githubusercontent.com/54243224/175335001-b1002012-c1f8-4f5d-856a-67511e5474d3.png)

2022-06-24 05:13 UTC, inifnite commented
Okay. I will make the said changes.

2022-06-25 05:51 UTC, inifnite commented
@zhaojj2209 @damithc is this fine?

https://user-images.githubusercontent.com/45487930/175760010-b5d670e1-22cb-43d4-a776-760135a8750f.mov

2022-06-25 07:12 UTC, damithc commented
> @zhaojj2209 @damithc is this fine?

I'm OK with this UX (others welcome to suggest alternatives). The second confirmation dialog need to emphasize the issue at hand, which is losing access e.g., the title of the dialog box should be revised accordingly.

2022-06-25 11:10 UTC, inifnite commented
Below is the changed dialog box, have a look at it.
Also should we add losing access warning for deleteAll courses from Recycle bin  operation  as well?? 
<img width="1117" alt="Screenshot 2022-06-25 at 4 34 20 PM" src="https://user-images.githubusercontent.com/45487930/175770961-dcc9fc1f-846c-4a57-bc60-d010dd194622.png">

2022-06-25 11:21 UTC, damithc commented
How about something like this?

> **This action will cause you to lose access to TEAMMATES!**
>--------
>If you delete _all_ courses of institute 'ABC', you will lose instructor access to TEAMMATES under the institution 'ABC'. To retain access, ensure you keep at least one course for each institution you are an instructor of. Are you sure you want to delete the course XYZ in institution 'ABC'?

Yes, the warning needs to be shown for 'delete all' as well, if applicable.

2022-06-25 12:08 UTC, inifnite commented
This is your last course registered on TEAMMATES for which you have instructor access. Deleting this course will remove your instructor access to TEAMMATES.
Are you sure you want to delete the course a11.a.a-demo in institution a?

Would this work in case of deleting last course of all courses??

2022-06-25 16:39 UTC, inifnite commented
Is this okay??

https://user-images.githubusercontent.com/45487930/175782765-f0522052-d6a6-45b5-ba7f-79f850225cc1.mov

2022-06-25 17:05 UTC, damithc commented
@inifnite I'm OK with this. Perhaps use red text for `loose access` (or highlight using yellow background)? I would like the second dialog to appear visibly different from the first one in an eye-catching way such that the user immediately realizes this is different and possibly more serious than the previous one.

2022-06-28 04:18 UTC, inifnite commented
for making second dialogue different from first, first has to be changed to warning and second to be remained as danger. Also, I tried changing color for `loose access` but it did not work. I just put sort of yellow background. have a look and let me know if this works??
<img width="960" alt="Screenshot 2022-06-28 at 9 43 53 AM" src="https://user-images.githubusercontent.com/45487930/176091298-4c62a9a5-c3d4-42d1-93f8-998b1a47d8ee.png">
<img width="960" alt="Screenshot 2022-06-28 at 9 44 04 AM" src="https://user-images.githubusercontent.com/45487930/176091304-b016c4b0-c8d9-4cd1-86e3-60dc6e9c87c8.png">

2022-06-28 06:25 UTC, damithc commented
> for making second dialogue different from first, first has to be changed to warning and second to be remained as danger. Also, I tried changing color for `loose access` but it did not work. I just put sort of yellow background. have a look and let me know if this works??
> <img alt="Screenshot 2022-06-28 at 9 43 53 AM" width="960" src="https://user-images.githubusercontent.com/45487930/176091298-4c62a9a5-c3d4-42d1-93f8-998b1a47d8ee.png">


Best not to change the style of this one, as its style should be consistent with other delete confirmations across TEAMMATES.

> <img alt="Screenshot 2022-06-28 at 9 44 04 AM" width="960" src="https://user-images.githubusercontent.com/45487930/176091304-b016c4b0-c8d9-4cd1-86e3-60dc6e9c87c8.png">

Also highlight `remove your instructor access` for good measure?

2022-06-29 04:44 UTC, inifnite commented
would this do??

https://user-images.githubusercontent.com/45487930/176353438-6f9b7b00-0bcf-4609-a57d-8eb98be23e11.mov

2022-07-02 03:04 UTC, inifnite commented
@zhaojj2209 Please have a look.

2022-07-02 08:00 UTC, zhaojj2209 requested changes
Code works, but code quality needs work. Some general comments:
- Ensure consistent code indentation
- Declaring constants is preferred over declaring variables and then reassigning them

2022-07-04 05:35 UTC, inifnite commented
@zhaojj2209 using else while having return in if block, gives lint error

2022-07-05 14:40 UTC, zhaojj2209 commented on src/web/app/pages-instructor/instructor-courses-page/instructor-courses-page.component.ts
> +        this.softDeletedCourses.forEach((courseToDelete: CourseModel) => {
Almost there! This suggested change was missed out.

2022-07-08 11:56 UTC, inifnite commented
Sorry for the delay

2022-07-08 12:57 UTC, NicolasCwy approved these changes
Changes look good to me! Nice work

2022-07-08 14:47 UTC, zhaojj2209 approved these changes
LGTM, thanks for the changes!

2022-07-30 06:36 UTC, merged