Yengah patch 2 for Teammates Issue #11754
TEAMMATES/teammates pull request #11983
Opened 2022-10-27 17:48 UTC by yengah

Albert Yu: modifications for Issue, Group Ass-3, Group 3

patch for Issue Instructor creating course: 'Institute' drop-down is empty if there are no active courses TEAMMATES/teammates#11754

Fixes #

located at: src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html (line 10)
located at: instructor-home-page.component.ts (line 80)

Ensure that you have:
- [x] Read and understood our PR guideline: https://teammates.github.io/teammates/process.html#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [x] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [x] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Patch**

This patch solves the issue by ensuring the field "Institution" always shows a value.

Situation prior to patch:
 * Clicking "Add New Course" from HOME enters COURSE page, and immediately displays the form.  Institution is NULL. This is the Issue (bug).
 
Situation after the patch:
 * Clicking "Add New Course" from HOME enters COURSE page, but does NOT immediately display the form.  Clicking "add new course" button displays the form.  Institution is no longer NULL.  Patch applied.

2022-10-27 19:15 UTC, jack44321 approved these changes

2022-11-03 05:47 UTC, yengah commented
> Frontend snapshot tests are failing, please look into the failed tests and either fix the code if the change is unintended, or update the snapshots if they are intended.

@zhaojj2209 Hello, what is the "InstructorHomePageComponent"?

2022-11-03 06:59 UTC, zhaojj2209 commented
> @zhaojj2209 Hello, what is the "InstructorHomePageComponent"?

I assume you are asking this question because of the frontend test error message and are unsure of where to find the corresponding test:
<img width="685" alt="Screenshot 2022-11-03 at 14 53 30" src="https://user-images.githubusercontent.com/54243224/199662258-0227dc33-4ee6-46c6-83d3-5520e4dff2d9.png">

In which case the answer can be found in the same error message:
<img width="835" alt="Screenshot 2022-11-03 at 14 53 56" src="https://user-images.githubusercontent.com/54243224/199662311-91a891ea-497e-4778-b804-a2764c83abda.png">

`instructor-home-page.component.spec.ts` contains the tests for `instructor-home-page.component.html` and `instructor-home-page.component.ts`, which are the two files you have edited in this PR.

2022-11-03 07:00 UTC, zhaojj2209 requested changes

2022-11-03 07:00 UTC, zhaojj2209 commented on src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
> +<!-- altered by Albert Yu  -->
Please remove this. Your GitHub credentials will be reflected in the commit history if this PR is merged.

2022-11-03 07:00 UTC, zhaojj2209 commented on src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.ts
> +  // altered by Albert Yu
Same here, please remove this credit.

2022-11-03 07:30 UTC, yengah commented
> > @zhaojj2209 Hello, what is the "InstructorHomePageComponent"?
> 
> I assume you are asking this question because of the frontend test error message and are unsure of where to find the corresponding test: <img alt="Screenshot 2022-11-03 at 14 53 30" width="685" src="https://user-images.githubusercontent.com/54243224/199662258-0227dc33-4ee6-46c6-83d3-5520e4dff2d9.png">
> 
> In which case the answer can be found in the same error message: <img alt="Screenshot 2022-11-03 at 14 53 56" width="835" src="https://user-images.githubusercontent.com/54243224/199662311-91a891ea-497e-4778-b804-a2764c83abda.png">
> 
> `instructor-home-page.component.spec.ts` contains the tests for `instructor-home-page.component.html` and `instructor-home-page.component.ts`, which are the two files you have edited in this PR.

@zhaojj2209 No, that's not what I meant.  What does "InstructorHomePageComponent" point to?  Which component?

2022-11-03 08:12 UTC, zhaojj2209 commented
> @zhaojj2209 No, that's not what I meant. What does "InstructorHomePageComponent" point to? Which component?

Still not sure what you're asking about. If you're asking about where to find it in the codebase, `InstructorHomePageComponent` is in `instructor-home-page.component.ts`? If you're asking about where to find it on the UI, it's the UI component that you see when on the instructor home page?

> The code needs some comments..

Any suggestions on what comments to add?

2022-11-04 00:43 UTC, yengah commented
> > @zhaojj2209 No, that's not what I meant. What does "InstructorHomePageComponent" point to? Which component?
> 
> Still not sure what you're asking about. If you're asking about where to find it in the codebase, `InstructorHomePageComponent` is in `instructor-home-page.component.ts`? If you're asking about where to find it on the UI, it's the UI component that you see when on the instructor home page?
> 
> > The code needs some comments..
> 
> Any suggestions on what comments to add?

Hello again, this patch will never pass those snapshot tests, unless they are modified.  I hesitate to modify the tests themselves, for reasons you ought to understand.  Please modify the tests if you want this patch to get through Teammates.  Thank you.

2022-11-04 04:01 UTC, damithc commented
> I hesitate to modify the tests themselves, for reasons you ought to understand. 

@yengah What are those reasons?

2022-11-04 21:29 UTC, yengah commented
> > I hesitate to modify the tests themselves, for reasons you ought to understand.
> 
> @yengah What are those reasons?

These tests really should not change all that often @damithc.  Logically if you think about it this makes good sense.  This is because these automated tests should be fairly foundational, as they are repeated over and over and over again..

2022-11-05 04:35 UTC, zhaojj2209 commented
> These tests really should not change all that often. Logically if you think about it this makes good sense. This is because these automated tests should be fairly foundational, as they are repeated over and over and over again..

Please read up on snapshot testing. Snapshot tests are used to guard against *unexpected* changes in UI components; when the changes are intended, the snapshot tests should be updated instead (which was what I've already mentioned when first informing you of the failed tests). Regardless of your hesitancy, the onus is on you to update the tests, we won't do it for you.

On another note, while this PR does resolve the issue, it's not ideal UX wise. The "Add New Course" button on the Home page now merely redirects users to the Courses page without opening the form, so users now have to click the "Add New Course" button twice. If possible, a solution where the Home page "Add New Course" button redirects users to the Courses page, opens the course form, and populates the institute dropdown would be preferred.

2022-11-05 04:59 UTC, damithc commented
> Please read up on snapshot testing. Snapshot tests are used to guard against _unexpected_ changes in UI components; when the changes are intended, the snapshot tests should be updated instead (which was what I've already mentioned when first informing you of the failed tests). Regardless of your hesitancy, the onus is on you to update the tests, we won't do it for you.

@yengah Yup, aligned to what @zhaojj2209 says here, different tests have different purposes; some tests need to evolve as the application behavior evolves. 
And yes, PR authors are expected to follow the norms of the project. If you want to propose a change to those norms (we are open to them too -- certainly there can be room for improvement in how we do things), they should be posted separately for discussion.

2022-11-05 07:06 UTC, yengah commented
> 

@damithc @zhaojj2209 I have a conclusion: because this PR is not logical UX-wise, it would be unwise to change the snapshot test code.

2022-11-05 07:52 UTC, damithc commented
> @damithc @zhaojj2209 I have a conclusion: because this PR is not logical UX-wise, it would be unwise to change the snapshot test code.

@yengah Yes. In fact, it would be unwise to merge it at all, in its current state. The remedy:
1. Update the PR to use a better UX, as suggested by @zhaojj2209 .
2. Update the tests accordingly

@zhaojj2209 any further inputs/alternative suggestions?

2022-11-05 13:27 UTC, zhaojj2209 commented
An ideal solution would be to populate the institute dropdown while still ensuring that the form is shown when clicking the Home page "Add New Course" button.

2022-12-06 08:48 UTC, zhaojj2209 commented
Closing due to inactivity. Feel free to reopen the PR if you would like to resume working on it.

2022-12-06 08:48 UTC, closed without merging