FeedbackRubricQuestionDetailsTest Added
TEAMMATES/teammates pull request #12025
Opened 2023-01-14 18:23 UTC by PedroLSF

Fixes #1501 

I've just tested the "validateQuestionDetails" method.

2023-01-17 08:29 UTC, zhaojj2209 requested changes
Please refer to our [contributing guidelines](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr). Your PR does not follow our PR naming conventions, please add the issue number to the PR title.

Also, for this specific issue, please modify your PR description from "Fixes" to "Part of". We do not want to close the issue just yet, as there are still other `Feedback*QuestionDetails` classes that would appreciate more testcases.

2023-01-17 08:29 UTC, zhaojj2209 commented on src/test/java/teammates/common/datatransfer/questions/FeedbackRubricQuestionDetailsTest.java
> +    public void testValidateQuestionDetails_invalidDescriptionSize() {
```suggestion
    public void testValidateQuestionDetails_invalidDescriptionSize_errorReturned() {
```
For consistency in test naming.

2023-01-17 08:29 UTC, zhaojj2209 commented on angular.json
> +    "analytics": "0b74d72c-3f85-4d9f-a963-b826e3f20e55",
Please remove this line.

2023-01-18 09:50 UTC, zhaojj2209 approved these changes
LGTM

2023-01-20 16:16 UTC, wkurniawan07 approved these changes
Thanks for your contribution!

2023-01-21 06:18 UTC, merged