[#] Testing getMinMaxPointErrors in FeedbackConstantSumQuestionDetails
TEAMMATES/teammates pull request #12033
Opened 2023-01-20 03:01 UTC by AlefMemTav

Fixes #

2023-01-20 08:40 UTC, zhaojj2209 requested changes
Thank you for your PR, however it does not follow our [contributing guidelines](https://github.com/TEAMMATES/teammates/blob/master/docs/process.md#step-4-submit-a-pr). Your PR:

- Does not address any specific issue
- Does not follow our PR naming conventions (PR title should contain the issue number for the issue to be addressed, not the PR number itself)
- Fails linting

Additionally, please remove all changes that are not related to the PR (e.g. `build.gradle`, `MANIFEST.MF`, `EmailGeneratorTest`).

2023-01-20 19:34 UTC, AlefMemTav commented
I don't know how to make these little corrections, so I'll leave it at that for now.

2023-01-22 14:00 UTC, AlefMemTav commented
It's OK now?

2023-01-22 16:25 UTC, wkurniawan07 commented
@AlefMemTav as far as private methods are concerned, they are usually tested with the public/protected method calling them, unless they are complicated enough to warrant their own test cases.
In this case, you may first want to check, maybe the tests you have written are already part of test cases for `validateResponsesDetails`?

2023-01-22 17:25 UTC, AlefMemTav commented
I checked and they are not part. See the Jacoco. I increased the coverage of the method.

2023-01-25 08:34 UTC, zhaojj2209 reviewed
As has been mentioned, private methods are usually tested via the public/protected methods calling them. You may want to consider modifying your testcases to be part of the two `testValidateResponseDetails_amongOptions` testcases instead, that way `getMinMaxPointErrors` can be tested without having to change the method from `private` to `protected`.

2023-01-25 08:34 UTC, zhaojj2209 commented on src/main/java/teammates/common/datatransfer/questions/FeedbackConstantSumQuestionDetails.java
> +    */
This isn't really needed as the method itself is self-explanatory enough.

2023-02-02 13:12 UTC, zhaojj2209 commented
@AlefMemTav Any updates on this PR?

2023-02-03 19:44 UTC, AlefMemTav commented
Next week I finish! I'm out of time because of university.

2023-02-03 19:44 UTC, closed without merging