[#12065] Student viewing rubric results: average doesn't match
TEAMMATES/teammates pull request #12066
Opened 2023-02-09 18:48 UTC by zhaojj2209

Fixes #12065

**Outline of Solution**

Fixes calculations for rubric statistics:

- Percentage average for each recipient is now calculated using the ratio of number of responses in each column to total number of responses.
- Overall weighted sum is calculated by summing the total chosen weight for each subquestion.

2023-02-09 19:03 UTC, samuelfangjw requested changes

2023-02-09 19:03 UTC, samuelfangjw commented on src/web/app/components/question-types/question-statistics/question-statistics-calculation/rubric-question-statistics-calculation.ts
> +      averages[i] = +(answersSum[i] * 100 / numResponses).toFixed(2);
Should add a check for if numResponses is 0

2023-02-09 19:39 UTC, samuelfangjw approved these changes

2023-02-10 02:26 UTC, jianhandev approved these changes
Looks correct.

2023-02-10 03:54 UTC, merged

2023-02-10 06:22 UTC, damithc commented
Thanks for the quick fix @samuelfangjw 
Let's release this quickly.