Fixes for Issue #12278
TEAMMATES/teammates pull request #12284
Opened 2023-03-28 08:17 UTC by meet0806

Fixes #12278 

**PR Checklist**

Ensure that you have:
- [x] Read and understood our PR guideline: https://teammates.github.io/teammates/process.html#step-4-submit-a-pr
  - [x] Added the issue number to the "Fixes" keyword above
  - [x] Titled the PR as specified in the abovementioned document
- [x] Made your changes on a branch other than `master` and `release`
- [x] Gone through all the changes in this PR and ensured that:
  - [x] They addressed one (and only one) issue
  - [x] No unintended changes were made
- [x] Run and passed static analysis: `./gradlew lint` and `npm run lint`
- [ ] Added/updated tests, if changes in functionality were involved
- [ ] Added/updated documentation to public APIs (classes, methods, variables), if applicable

**Outline of Solution**

Added Style for "Add New Course" Section.

2023-03-28 09:41 UTC, domlimm requested changes
@meet0806 Thanks for contributing! As TEAMMATES uses [bootstrap](https://getbootstrap.com/docs/5.2/getting-started/introduction/) for styling, etc., let's try to make use of that.

2023-03-28 09:41 UTC, domlimm commented on src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
> +  <div class="col-4" style="margin-top: auto;">
Let's try to use the css classes provided by bootstrap, instead of inline styling.

2023-03-28 09:53 UTC, weiquu commented
Thanks @meet0806, apart from @domlimm's comment please also remember to update the tests. You can find more information on running the tests [here](https://teammates.github.io/teammates/development.html#testing) as well as some background on snapshot testing [here](https://teammates.github.io/teammates/snapshot-testing.html)

2023-03-28 16:53 UTC, domlimm requested changes
@meet0806 One last change!

Also, just a nit to not have double quotes `"` in your branch name as it can cause issues on [Windows](https://stackoverflow.com/questions/66113037/git-pull-in-windows-doesnt-work-when-the-branch-name-had-double-quotes) when switching branches. Branch name of `X-Y-Z-A-B-C` is fine 👍🏻

2023-03-28 16:53 UTC, domlimm commented on src/web/app/pages-instructor/instructor-home-page/instructor-home-page.component.html
> +  <div class="col mt-auto">
One last bit, let's bring back `col-4` and not remove it though it does not have any effect but the container holding the other buttons has a width contained with `col-8`.
```suggestion
  <div class="col-4 mt-auto">
```

Update snapshot too 👍🏻

2023-03-28 17:16 UTC, closed without merging

2023-03-29 01:57 UTC, domlimm commented
@meet0806 Hey meet, why did you close the PR? I saw that you made another branch with the final change. You've deleted the old branch too. Please open another PR to fix the issue so we can have this merged 👍

2023-03-29 02:25 UTC, meet0806 commented
Hey @domlimm Another PR is Already created [#12295]

2023-03-29 03:26 UTC, domlimm commented
@meet0806 Thanks! Will get to it soon.