[#12293] Admin logs page: Extension of query start/end time is not reflected in search range
TEAMMATES/teammates pull request #12342
Opened 2023-04-05 04:15 UTC by gordonscottkolb

Fixes #12293

2023-04-05 05:55 UTC, kevin9foong commented
hi @gordonscottkolb, thanks for the PR! I will be reviewing this PR shortly.

2023-04-06 06:42 UTC, domlimm reviewed
@gordonscottkolb Clean solution 👍🏻 Just a minor nit in the comment.

2023-04-06 06:42 UTC, domlimm commented on src/web/services/datetime.service.ts
> +     */
Minor nit.

```suggestion
    /**
     * Gets a DateFormat and a TimeFormat from a DateFormat and a TimeFormat Delta changed by deltaMinutes.
     *
     * @param deltaMinutes accepts a postive or negative number.
     */
```

2023-04-06 07:13 UTC, kevin9foong commented
Apart from @domlimm's comment, looks good to me. Thanks for your contribution!

2023-04-09 11:18 UTC, domlimm requested changes
@gordonscottkolb Please fix the lint error. Could refer to other `*.ts` files to see how the jsdocs is written. Also, please update your branch so we can merge it. Thanks!

2023-04-09 18:09 UTC, kevin9foong commented on src/web/services/datetime.service.ts
> +     * @param deltaMinutes accepts a postive or negative number.
Just need to add the description for the date and time here

2023-04-10 03:54 UTC, domlimm requested changes
@gordonscottkolb Last bit to update, and we should be good to merge! Thanks!

2023-04-10 03:54 UTC, domlimm commented on src/web/services/datetime.service.ts
> +     * Converts a a single Date instance to a DateFormat object and a TimeFormat object.
Sorry just caught this.
```suggestion
     * Converts a single Date instance to a DateFormat object and a TimeFormat object.
```

2023-04-10 03:54 UTC, domlimm commented on src/web/services/datetime.service.ts
> +     * @param time accepts a TimeFormat object.
```suggestion
     * @param date current date to change.
     * @param time current time to change.
```

2023-04-10 05:44 UTC, domlimm approved these changes
@gordonscottkolb LGTM! Thank you for your contribution!

2023-04-10 09:05 UTC, kevin9foong approved these changes
LGTM!

2023-04-11 00:58 UTC, gordonscottkolb commented
@kevin9foong @domlimm is there anything else I need to do for this issue, or will someone merge the pull request now?

2023-04-11 02:19 UTC, domlimm commented
@gordonscottkolb That will be all. Thanks Gordon! 😃

2023-04-13 06:04 UTC, merged