[#12334] Instructor courses page: fix copy instructors from other courses modal checkbox
TEAMMATES/teammates pull request #12369
Opened 2023-04-12 13:32 UTC by judith-n

Fixes #12334

2023-04-12 14:44 UTC, cedricongjh requested changes
Hi @judith-n, thank you for your pull request!

Functionally, the checkbox now works:
![image](https://user-images.githubusercontent.com/67156011/231492333-00d5c126-8bda-44f7-b63e-048f0d98e439.png)

Let's also take the chance to standardise it's appearance, as it is different from the other checkboxes throughout the application:
![image](https://user-images.githubusercontent.com/67156011/231493031-209bec00-547e-4083-973c-0154621d7a5e.png)
![image](https://user-images.githubusercontent.com/67156011/231493082-5c5ca33f-57af-42ab-9b7b-370e18579968.png)

This is most likely due to the `form-control` class of the input, which sets the checkbox height and width. Removing the `form-control` class from the input that should result in the checkbox looking the same as the rest.

Do make the change and

2023-04-12 14:45 UTC, cedricongjh commented on src/web/app/pages-instructor/instructor-course-edit-page/copy-instructors-from-other-courses-modal/copy-instructors-from-other-courses-modal.component.html
> +                          <input id="enabled-checkbox" [disabled]="isCopyingSelectedInstructors" type="checkbox" class="form-control form-check-input no-shadow" [(ngModel)]="instructorCandidate.isSel
```suggestion
                          <input id="enabled-checkbox" [disabled]="isCopyingSelectedInstructors" type="checkbox" class="form-check-input no-shadow" [(ngModel)]="instructorCandidate.isSelected">
```

2023-04-13 08:26 UTC, judith-n commented
@cedricongjh thank you so much! :)

2023-04-13 08:31 UTC, cedricongjh approved these changes
LGTM, thank you for your contribution to TEAMMATES!

2023-04-13 11:50 UTC, zhaojj2209 approved these changes
LGTM!

2023-04-13 11:51 UTC, merged