[#12421] Feature/response comment essay question
TEAMMATES/teammates pull request #12426
Opened 2023-05-12 09:14 UTC by ellaella12

Fixes #

**Outline of Solution**

2023-05-15 10:10 UTC, cedricongjh commented on src/test/java/teammates/ui/webapi/GetFeedbackResponsesActionTest.java
> +                dataBundle.feedbackResponseComments.get("comment1FromInstructor1Question2");
Given that the aim is for students to be able to comment on their responses, I think we should change this test to be a comment from a student instead?

2023-05-15 10:12 UTC, cedricongjh requested changes
Thank you for the PR! 

However, there appears to be errors when I try to submit a feedback response comment on non-MCQ and MRQ question types:

<img width="677" alt="image" src="https://github.com/TEAMMATES/teammates/assets/67156011/ac29927f-8567-4802-a5d3-b9e439aa6a67">

Do fix this and address the other comment regarding testing, thank you!

2023-05-17 00:03 UTC, ellaella12 commented
Hi, thank you for the review! may I check which qn would you be referring to that returns that error message? or how to replicate this? 
as i submitted comments for different qn types and got this
![image](https://github.com/TEAMMATES/teammates/assets/120079323/622ff107-83d2-4d6e-b88f-c78f99e7f992)

Thank you!

2023-05-17 00:16 UTC, ellaella12 commented
Hi, thank you for the review!

May I check how do i replicate the error message above? 
I tried submitting for different qn types and got this
![image](https://github.com/TEAMMATES/teammates/assets/120079323/72f5194f-229e-41ac-ad4b-e91dd16e5f76)

2023-05-18 09:35 UTC, cedricongjh commented
> Hi, thank you for the review!
> 
> May I check how do i replicate the error message above? I tried submitting for different qn types and got this ![image](https://user-images.githubusercontent.com/120079323/238799000-72f5194f-229e-41ac-ad4b-e91dd16e5f76.png)

HI @ellaella12, I tried again but did not run into the error, so no worries about this!

2023-05-18 13:42 UTC, cedricongjh requested changes
Hi @ellaella12, there's another thing to consider that I missed out, we need to add in the student's comment in the downloaded result as well:

Click download result:
<img width="1241" alt="image" src="https://github.com/TEAMMATES/teammates/assets/67156011/8a801c6b-5733-4bcc-864c-3d1fe6c25e81">

The csv has `Giver comment` column for MCQ and MRQ type questions
![Uploading image.png…]()

Do add that in and re-request a review, thank you!

2023-05-21 08:44 UTC, ellaella12 commented
Hi, I have included the givers comment for all question types into the csv
for e.g, the images below, comment text are `cx` 
![image](https://github.com/TEAMMATES/teammates/assets/120079323/61239bac-2e78-4cb9-b2d6-9c69e14e94b4)
![image](https://github.com/TEAMMATES/teammates/assets/120079323/53577f39-21c3-4ce9-82f3-9921c0d3be3f)
![image](https://github.com/TEAMMATES/teammates/assets/120079323/7c128c3a-697d-47d1-b6f6-e9a9cc894af1)


Thank you!

2023-05-22 20:23 UTC, cedricongjh reviewed
LGTM, thank you for working on this project!

2023-05-23 02:42 UTC, kevin9foong commented
@cedricongjh, not sure if this is ok to be merged

2023-05-23 07:04 UTC, cedricongjh commented
> @cedricongjh, not sure if this is ok to be merged

It needs a final review from @zhaojj2209, so not yet!

2023-05-26 14:06 UTC, zhaojj2209 commented
Apologies for the delay, will try to get to this PR within the next few days.

2023-05-27 09:44 UTC, ellaella12 commented
sure, no rush, thank you!

2023-05-28 14:35 UTC, zhaojj2209 commented
Great work so far!

One bug I've found: for distribute points questions and team contribution questions, the component state is not being updated correctly and only updates on refresh. See below video where the comment text editor is still active after saving the comment, and attempting to submit again causes an error. For deletion, the comment does not disappear immediately after deleting, and an error will pop up when attempting to submit again.

https://github.com/TEAMMATES/teammates/assets/54243224/a7e03a4f-d600-43c0-a0d6-584302ab782b

For reference, the correct behaviour is as follows:

https://github.com/TEAMMATES/teammates/assets/54243224/38c5ecda-da21-4144-bbaa-cb9de1690ea0

As for your question regarding the saving of comments when saving all questions, I agree that it should be in a separate PR, with a separate issue to track it.

2023-06-17 04:52 UTC, ellaella12 commented
Hi thank you for the review! I have fixed the bug and its able to delete and submit in real time now.
I have a few questions:

1. the Bug is fixed by updating the model before emitting an event to the parent, like how 2 way binding is done in angular docs https://angular.io/guide/two-way-binding. Originally, it doesn't update the model but just sends the updated values to the parent. I am unsure why it works and why do we have to update the model before emitting event to parent?

Is it because the stale child model override the parent model?

2. From a quick check, it seems the `CommentEditFormModel.isUsingCustomVisiblities` is not used as the comment follows the question's visibility. Furthermore this visibilities is set to empty after a comment is edited. Is it used somewhere?

3. After switching to master branch and running e2e tests, it is failing at the same test case as this pr.

2023-06-19 13:43 UTC, zhaojj2209 commented
1. > Is it because the stale child model override the parent model?

From what I know that is indeed the case. Thanks for helping to fix this!

2. `isUsingCustomVisibilities` is used in `comment-edit-form.component.ts`.

3. We will help to monitor the E2E test runs, sometimes tests take multiple runs to pass.

2023-06-20 03:02 UTC, ellaella12 commented
Hi, sorry about that I have fixed it, it should work now. Thank you!

[TEAMMATES - Online Peer Feedback_Evaluation System for Student Team Projects (1).webm](https://github.com/TEAMMATES/teammates/assets/120079323/8ce463cd-da11-422b-a47a-83dc85e35a89)

2023-06-23 09:41 UTC, ellaella12 commented
Hi sorry about that, I have made a fix, it's working now
[TEAMMATES - Online Peer Feedback_Evaluation System for Student Team Projects (1).webm](https://github.com/TEAMMATES/teammates/assets/120079323/f1ed8149-c63a-4c19-950e-fdcb42b3ca06)

2023-06-24 14:34 UTC, zhaojj2209 commented
Thanks for the fix, great work so far!

One last issue I've managed to uncover: after submitting a feedback response to a distribute points (recipients) question, reloading the page and attempting to submit it again without making any changes will give the following error:

<img width="714" alt="Screenshot 2023-06-24 at 22 17 14" src="https://github.com/TEAMMATES/teammates/assets/54243224/65628079-aca8-400c-997f-56e2b3f281ad">

The issue doesn't appear if you make any changes to the response before submitting the response again, and the issue is not present for any other question type.

Let me know if you need more clarifications on when the bug occurs.

This should be the last bug left (crosses fingers), after this the PR should be good to go 💪

2023-06-28 14:49 UTC, ellaella12 commented
Hi, thank you for the review! Sorry for the numerous bugs. have made a fix for submission without changing answer, by changing `QuestionConstraintComponent` to check is valid only in `ngOnInit()` when both the `recipientSubmissionForms` and `questionDetails` has initialized. 
Originally, the check is valid is called right after `recipientSubmissionForms`, so default `questionDetails` are used = wrong validity check. Is this fix ok?
[TEAMMATES - Online Peer Feedback_Evaluation System for Student Team Projects (2).webm](https://github.com/TEAMMATES/teammates/assets/120079323/605c3aa7-805c-4c14-8694-0f871c7ef264)


For this ```Edit: My bad, found one more bug 🙇‍♀️ The response comments are not being submitted when clicking the "Submit Responses to All Questions" button, do look into it.```
The comment dated May 28 ``As for your question regarding the saving of comments when saving all questions, I agree that it should be in a separate PR, with a separate issue to track it.```
Or should the change be implemented in this pr?

2023-07-02 07:31 UTC, zhaojj2209 approved these changes
Thank you so much for the work done!

@wkurniawan07 Now that we are allowing feedback response participants to add comments for every question type, should we evaluate whether we should do the same for instructor comments as well? Currently instructors are allowed to add comments on all question types except team contribution.

2023-07-02 07:38 UTC, damithc commented
> @wkurniawan07 Now that we are allowing feedback response participants to add comments for every question type, should we evaluate whether we should do the same for instructor comments as well? Currently instructors are allowed to add comments on all question types except team contribution.

@zhaojj2209 Perhaps it is better to leave out team contribution questions from this feature. The values shown to instructors could be different from those shown to students (due to normalizing etc.), so the comments instructors enter could be misleading to students.

2023-07-02 10:45 UTC, cedricongjh approved these changes
LGTM, great work on this!

2023-07-22 15:29 UTC, merged