[#1501] Create Unit Tests for Feedback*QuestionDetails classes
TEAMMATES/teammates pull request #12479
Opened 2023-06-17 16:42 UTC by aorlandou

Part of #1501 

**Outline of Solution**

I added a few tests to cover the shouldChangesRequireResponseDeletion method for 2 classes:
- FeedbackMsqQuestionDetails
- FeedbackNumericalScaleQuestionDetails

2023-06-21 20:14 UTC, cedricongjh approved these changes
lgtm, thank you for your contribution to TEAMMATES

2023-06-23 02:35 UTC, EuniceSim142 requested changes
Other than one change, lgtm!

2023-06-23 02:35 UTC, EuniceSim142 commented on src/test/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetailsTest.java
> +        numDetails.setMinScale(3);
This should set min scale for `newNumDetails`. 
```suggestion
        newNumDetails.setMinScale(3);
```

2023-06-23 02:35 UTC, EuniceSim142 commented on src/test/java/teammates/common/datatransfer/questions/FeedbackNumericalScaleQuestionDetailsTest.java
> +        numDetails.setMaxScale(2);
Same thing here. Please also change all the other tests in this file.

2023-06-23 12:12 UTC, aorlandou commented
Hey @EuniceSim142 thank you for the review you are correct. I made the necessary changes hopefully now it is ready to be merged. :grin:

2023-06-24 02:42 UTC, EuniceSim142 approved these changes
Lgtm, thanks for contributing to Teammates!

2023-06-24 14:30 UTC, merged