[#12059] Separate stable and unstable E2E tests
TEAMMATES/teammates pull request #12515
Opened 2023-07-14 09:42 UTC by domoberzin

Fixes #12059 

**Outline of Solution**

Moves tests that frequently require multiple test runs into a separate Github job within the same E2E testing workflow.

 

Created a new command within build.gradle to run only tests specified in  `src/e2e/resources/testng-unstable-e2e.xml`

2023-07-16 04:22 UTC, wkurniawan07 requested changes
The changes from this PR doesn't solve the problem. It is merely separating to a different step, which means if all 5 attempts failed, everything (including the stable tests) needs to be started from the beginning.

2023-07-16 14:14 UTC, wkurniawan07 requested changes

2023-07-16 14:14 UTC, wkurniawan07 commented on .github/workflows/e2e.yml
> +  E2E-testing-unstable:
Instead of duplicating, the unstable variant should be defined with the `matrix` option

2023-07-16 14:14 UTC, wkurniawan07 commented on build.gradle
> +        options.suites isFirstTry ? "src/e2e/resources/testng-unstable-e2e.xml" : file("${buildDir}/reports/e2e-unstable-test-try-${id - 1}/testng-failed.xml")
Similarly here, instead of duplicating the entire thing, consider using `-D` or `-P` flag to differentiate the XML file being used

2023-07-27 08:47 UTC, weiquu commented
@wkurniawan07 / any other contributors free to review this PR? I'm not familiar with GitHub workflows...

Also, should the "E2E-testing (firefox)" check still be there? Not sure if by updating the workflow it should be removed:
![Screenshot 2023-07-27 at 4 47 11 PM](https://github.com/TEAMMATES/teammates/assets/48304907/d15b3833-4b0b-46e4-ae56-8bcc1164c910)

2023-07-27 10:32 UTC, wkurniawan07 approved these changes

2023-07-27 12:26 UTC, merged