[#12551] Sessions page fix
TEAMMATES/teammates pull request #12561
Opened 2023-08-18 16:18 UTC by DamiGbs

Fixes #12551

**Outline of Solution**
Did the same as in PR #12550. Only that i added a error Toast:
![image](https://github.com/TEAMMATES/teammates/assets/118913102/7766711e-195c-4fcd-8333-3f6ed9b661f9)

2023-08-19 03:25 UTC, weiquu commented
Hi @DamiGbs, thanks for submitting this PR. I noted that there are a lot of formatting changes introduced. Do revert those changes in accordance to our [documentation](https://teammates.github.io/teammates/process.html#step-3-fix-the-issue), which states under point 3 that "no unrelated changes are [to be] introduced in the branch. This includes unnecessary formatting changes". As far as I can tell, the relevant changes are only to 5 lines.

Do also note that we typically align multi-line parameters to the first parameter (e.g. line 109), or add an additional tab to indicate that the parameter list is still ongoing. When we chain operations together on a variable, we also either align to the first operation or add an additional tab as a visual indicator (e.g. line 164).

We will proceed to review your PR after the changes have been made.

2023-08-19 09:40 UTC, DamiGbs commented
Hi @weiquu, should be fixed now. Looks like i had a different formatter in VsCode that changed the whole formatting of the code.

2023-08-21 15:19 UTC, cedricongjh requested changes
Hi @DamiGbs, thank you for your PR, do make the requested changes and re-request for a review!

2023-08-21 15:19 UTC, cedricongjh commented on src/web/app/pages-instructor/instructor-sessions-page/instructor-sessions-page.component.ts
> +        }
This can be removed as the error toast already shows without it

2023-08-22 04:01 UTC, cedricongjh approved these changes
LGTM! Thank you for your contribution to TEAMMATES

2023-09-06 23:13 UTC, jasonqiu212 approved these changes
LGTM!

2023-09-06 23:18 UTC, merged