[#12314] Update: Popover appears in front of modal blocking buttons
TEAMMATES/teammates pull request #12573
Opened 2023-09-04 00:17 UTC by Mex7180

Fixes #12314

**Outline of Solution**

 
- add mouse enter event to enable the tooltip
- close tooltip when the button to save the responses is clicked

**Laptop size:**
<img width="1241" alt="Bildschirmfoto 2023-09-04 um 02 13 40" src="https://github.com/TEAMMATES/teammates/assets/90850610/788db777-0720-41be-8acf-e1a5f2579fc9">
<img width="1219" alt="Bildschirmfoto 2023-09-04 um 02 13 54" src="https://github.com/TEAMMATES/teammates/assets/90850610/38d582d2-82f2-45f5-bcec-e7284f494cf9">

**Mobile size:**
<img width="468" alt="Bildschirmfoto 2023-09-04 um 02 14 16" src="https://github.com/TEAMMATES/teammates/assets/90850610/37928c70-1b81-46fa-a85e-17a1ea181cb0">
<img width="478" alt="Bildschirmfoto 2023-09-04 um 02 14 27" src="https://github.com/TEAMMATES/teammates/assets/90850610/94e25074-eac9-4cb6-9fa6-03c075e799e8">

2023-09-04 10:28 UTC, Mex7180 commented
Ready for review :D

2023-09-04 17:46 UTC, Mex7180 commented
Ready for review :D

2023-09-04 20:39 UTC, cedricongjh approved these changes
LGTM, thank you for your contribution to TEAMMATES!

2023-09-09 03:55 UTC, jasonqiu212 requested changes
Thanks for contributing to TEAMMATES! @Mex7180 

Just a very small nitpick on the indentation! Other than that, LGTM!

2023-09-09 03:55 UTC, jasonqiu212 commented on src/web/app/components/question-submission-form/question-submission-form.component.html
> +                   (click)="saveFeedbackResponses(); tooltip.close();"[disabled]="isSavingResponses || isSubmissionDisabled">
```suggestion
                  (click)="saveFeedbackResponses(); tooltip.close();"[disabled]="isSavingResponses || isSubmissionDisabled">
```

2023-09-13 03:14 UTC, jasonqiu212 approved these changes
LGTM! Thanks for contributing to TEAMMATES!

2023-09-13 03:14 UTC, merged