[#12571] Instructors Edit Feedback Session: Instructor is able to edit submission opening time to an earlier timing
TEAMMATES/teammates pull request #12580
Opened 2023-09-06 13:42 UTC by dlimyy

Fixes #12571 

**Outline of Solution**

I created a new method called `triggerSubmissionOpeningDateModelChange` which is triggered when the instructor chooses a date in the date picker for the submission opening time. When the instructor changes the date to the earliest possible date, the `submissionStartTime` of the model will change accordingly to the earliest possible time for that date. Since the hours that the instructor are all in 0 minutes(with the exception of 23:59), I created another function `configureSubmissionOpeningTime` to configure the time properly.

2023-09-10 14:40 UTC, dlimyy commented
I have fixed the bug regarding the case where the save button is disabled when the user passes in an invalid submission opening time. As seen below, the fields are now editable when there is an error.

https://github.com/TEAMMATES/teammates/assets/97420966/1bf5b137-614d-4eea-b231-d294d9be92f9

2023-09-10 14:42 UTC, dlimyy commented
This PR is also now ready for review

2023-09-12 15:14 UTC, cedricongjh requested changes
Thank you for your PR! (And great job finding this edge case)

Left a few comments that I think should be addressed.

Also, I've discovered that when switching to the min date, the time always defaults to the min time, even when the time selected is valid (e.g. 13th Sept, 2359 is selected, but switching to 12th Sept (the minDate) causes the time to change)

Do fix the issues and re-request a review!

2023-09-12 15:14 UTC, cedricongjh commented on src/web/app/components/session-edit-form/session-edit-form.component.ts
> +    }
time.hour === 23 && time.minute > 0 falls under the if branch case as well, I believe that the branches should be switched, could we also add unit tests for this method as well? (especially given that it deals with time)

2023-09-12 15:14 UTC, cedricongjh commented on src/web/app/components/session-edit-form/session-edit-form.component.ts
> +    if (JSON.stringify(minDate) === JSON.stringify(date)) {
not a huge fan of this although it works, could we add a DateFormat comparision function in DateTimeService and use that here? (do add unit tests for the comparision function as well!)

2023-09-14 13:52 UTC, dlimyy commented
Hi @cedricongjh, thanks for reviewing of my PR and pointing out the bugs in my code! I have fixed the changes pointed out and added unit tests for all the methods requested. In addition, I have also solved the problem where switching the date to min date will always cause the time to revert to min time.

2023-09-21 14:52 UTC, cedricongjh commented on src/web/app/components/session-edit-form/session-edit-form.component.ts
> +      [field]: date,
nit: perhaps we could use `triggerModelChange` here

2023-09-21 14:53 UTC, cedricongjh requested changes
Besides that one nit, LGTM!

2023-09-22 06:31 UTC, dlimyy commented
Hi @cedricongjh, I have changed it to triggerModelChange. Ready for review!

2023-09-23 13:22 UTC, cedricongjh approved these changes
LGTM, thank you for your contribution!

2023-09-24 23:23 UTC, jasonqiu212 approved these changes
LGTM! Thank you for spotting this edge case and fixing it :)

2023-09-24 23:24 UTC, merged