[#12588] Added unit tests for CommentTableModalComponent
TEAMMATES/teammates pull request #12609
Opened 2023-10-18 01:12 UTC by kenneySiu

Part of #12588

**Outline of Solution**
Added unit tests for the following methods in CommentTableModalComponent
ngOnChanges,
triggerDeleteCommentEvent,
triggerUpdateCommentEvent,
triggerSaveNewCommentEvent,
triggerModelChange

2023-10-18 13:22 UTC, cedricongjh requested changes
thank you for the PR, just a few minor nits!

2023-10-18 13:22 UTC, cedricongjh commented on src/web/app/components/comment-box/comment-table-modal/comment-table-modal.component.spec.ts
> +    };
let's abstract this out for multiple tests to use

2023-10-18 13:22 UTC, cedricongjh commented on src/web/app/components/comment-box/comment-table-modal/comment-table-modal.component.spec.ts
> +  it('should trigger an event to delete comment from comments table', () => {
```suggestion
  it('should emit a DeleteCommentEvent with the correct index when triggerDeleteCommentEvent is called', () => {
```

let's follow this format when describing tests for event emissions, do the same for the other tests that emit events

2023-10-19 12:57 UTC, kenneySiu commented
Ready for review

2023-12-02 14:48 UTC, merged