[#12588] Add unit test for every method in CommentRowComponent
TEAMMATES/teammates pull request #12612
Opened 2023-10-19 06:58 UTC by ThomasGreen123

Fixes [https://github.com/TEAMMATES/teammates/issues/12588]

Outline of Solution
Add unit test for every method in CommentRowComponent

**Outline of Solution**

2023-10-19 12:05 UTC, ThomasGreen123 commented
Ready for review

2023-10-19 17:35 UTC, cedricongjh commented on src/web/app/components/comment-box/comment-row/comment-row.component.spec.ts
>    });
the expectations in some of the tests are incorrect, let's create spys:

```javascript
  const spyVisibilityStateMachine: any = {
    allowAllApplicableTypesToSee: jest.fn(),
    applyVisibilitySettings: jest.fn(),
    getVisibilityTypesUnderVisibilityControl: jest.fn()
  }

  const spyCommentService: any = {
    getNewVisibilityStateMachine: jest.fn().mockReturnValue(spyVisibilityStateMachine)
  };
```

and provide them in configureTestingModule: 

```javascript
providers: [
  { provide: FeedbackResponseCommentService, useValue: spyCommentService },
]
```

2023-10-19 17:36 UTC, cedricongjh commented on src/web/app/components/comment-box/comment-row/comment-row.component.spec.ts
> +      expect(component.visibilityStateMachine).toBeDefined();
`expect(spyVisibilityStateMachine.allowAllApplicableTypesToSee).toHaveBeenCalled()` should be here, and same goes for the other tests, ensure that the visibilityStateMachine and commentService are called with the appropriate parameters

2023-10-19 17:37 UTC, cedricongjh commented on src/web/app/components/comment-box/comment-row/comment-row.component.spec.ts
> +  });
another example of a place where we should expect the visibilityStateMachine to be called with a parameter

```javascript
    expect(spyVisibilityStateMachine.applyVisibilitySettings).toHaveBeenCalledWith({
      SHOW_COMMENT: [CommentVisibilityType.GIVER, CommentVisibilityType.INSTRUCTORS],
      SHOW_GIVER_NAME: [CommentVisibilityType.GIVER, CommentVisibilityType.INSTRUCTORS]
    });
```

2023-10-19 17:38 UTC, cedricongjh requested changes
thank you for your PR!

do take a look at the comments and make the changes accordingly

2023-10-19 19:11 UTC, ThomasGreen123 commented
Thank you for giving me these instructions! I have made changes accordingly. Does this meet requirements now? Feel free to tell me if this requires further improvement.

2023-10-21 14:14 UTC, cedricongjh requested changes
hey @ThomasGreen123, you're almost there with this PR, let's `expect` that the  allowAllApplicableTypesToSee and getNewVisibilityStateMachine are called with the correct parameters, similar to the example i provided earlier with `applyVisibilitySettings`

2023-10-24 13:22 UTC, ThomasGreen123 commented
Yeah, I have made changes accordingly. By the way, can you assign one more class to me in https://github.com/TEAMMATES/teammates/issues/12588?

2023-10-26 23:53 UTC, ThomasGreen123 commented
Yeah, I have made changes accordingly. Ready for review.

2023-10-28 18:34 UTC, cedricongjh requested changes
apologises for the late review, just 2 very small changes and we're good to go!

2023-10-28 18:34 UTC, cedricongjh commented on src/web/app/components/comment-box/comment-row/comment-row.component.spec.ts
> +      expect(spyVisibilityStateMachine.allowAllApplicableTypesToSee).toHaveBeenCalledWith();
it's fine to keep this as toHaveBeenCalled, since there's no params

2023-10-28 18:34 UTC, cedricongjh commented on src/web/app/components/comment-box/comment-row/comment-row.component.spec.ts
> +      expect(spyVisibilityStateMachine.allowAllApplicableTypesToSee).toHaveBeenCalledWith();
same here

2023-10-28 18:34 UTC, cedricongjh commented on src/web/app/components/comment-box/comment-row/comment-row.component.spec.ts
> +      expect(spyCommentService.getNewVisibilityStateMachine).toHaveBeenCalledWith([]);
let's set questionShowResponsesTo in the component, and check that getNewVisibilityStateMachine is called with the appropriate params

2023-10-29 03:01 UTC, ThomasGreen123 commented
Thank you for your advice. I've made relevant changes. Ready for review.

2023-10-30 09:22 UTC, cedricongjh approved these changes
LGTM, thank you for the work on this!

2023-11-30 07:40 UTC, merged