[#12588] Add unit tests for FeedbackPathPanelComponent
TEAMMATES/teammates pull request #12613
Opened 2023-10-19 20:41 UTC by JYH11

Part of #12588 

**Outline of Solution**
Add unit tests for FeedbackPathPanelComponent

2023-10-21 14:07 UTC, cedricongjh requested changes
a couple of comments, and also changeGiverRecipientType function is not being tested here, do add tests for that

2023-10-21 14:07 UTC, cedricongjh commented on src/web/app/components/feedback-path-panel/feedback-path-panel.component.spec.ts
> +    expect(result).toEqual(customNumber);
```suggestion
    const emitSpy = jest.spyOn(component.customNumberOfEntitiesToGiveFeedbackTo, 'emit');
    expect(emitSpy).toHaveBeenCalledWith(customNumber);
```
let's test the emit event this way, same goes for the rest of the tests

2023-10-22 00:11 UTC, JYH11 commented
Thanks for the comment, I've fixed the issue that you've mentioned. 
Additionally, I'd added changeGiverRecipientType test case, please check it!
Thanks!

2023-10-22 18:48 UTC, cedricongjh requested changes
almost there, some more branches to test in changeGiverRecipientType, do ensure that all the branches are tested

2023-10-22 18:48 UTC, cedricongjh commented on src/web/app/components/feedback-path-panel/feedback-path-panel.component.spec.ts
> +  });
let's add a test case for this branch:
`if (allowedRecipientTypes.indexOf(recipientType) === -1)`

let's also check that `triggerModelChangeBatch` emits (or does not emit in the case of this.model.isUsingOtherFeedbackPath being false) with the correct params using spys, in both the if and else blocks

2023-10-23 15:38 UTC, JYH11 commented
I think I'm pretty sure to cover all the branchs, test coverage seems bit higher then previous one!
Anyway, thanks for the comment, ready for review now!

2023-10-25 09:40 UTC, cedricongjh requested changes
almost there, just a few minor changes!

2023-10-25 09:40 UTC, cedricongjh commented on src/web/app/components/feedback-path-panel/feedback-path-panel.component.spec.ts
> +    const firstToggle = component.isSubMenuOpen(menu);
let's add an expectation here that firstToggle is true

2023-10-25 09:40 UTC, cedricongjh commented on package-lock.json
do remove this, otherwise we are unable to merge this PR

2023-10-25 09:40 UTC, cedricongjh commented on src/web/app/components/feedback-path-panel/feedback-path-panel.component.spec.ts
> +    });
small nit here, let's add another test to check for `isUsingOtherFeedbackPath = false` as well and ensure that emitSpy is not called

2023-10-25 15:22 UTC, JYH11 commented
Thanks for the comment! I've fixed the issues, please check it!

2023-10-26 15:03 UTC, cedricongjh approved these changes
LGTM! thank you for your contribution

2023-10-29 00:32 UTC, jasonqiu212 approved these changes
LGTM!

2023-10-29 00:33 UTC, merged