[#12588] Added unit tests for SessionEditFormComponent
TEAMMATES/teammates pull request #12627
Opened 2023-10-27 10:37 UTC by kenneySiu

Part of #12588 

**Outline of Solution**
Added unit tests for the following methods in SessionEditFormComponent
triggerModelChange,
triggerSubmissionOpeningDateModelChange,
courseIdChangeHandler,
submitFormHandler,
cancelHandler,
deleteHandler,
copyHandler,
copyOthersHandler,
closeEditFormHandler

2023-10-28 19:19 UTC, cedricongjh requested changes
some changes,

also minTimeForSubmissionEnd, minDateForSessionVisible, minTimeForSessionVisible, maxDateForSessionVisible, maxTimeForSessionVisible, minDateForResponseVisible, minTimeForResponseVisible are currently not tested as well, do add tests for those

2023-10-28 19:19 UTC, cedricongjh commented on src/web/app/components/session-edit-form/session-edit-form.component.spec.ts
> +    expect(configureSubmissionOpeningTimeSpy).toHaveBeenCalledWith(minTime);
we should also expect triggerModelChange to have been called here

2023-10-28 19:19 UTC, cedricongjh commented on src/web/app/components/session-edit-form/session-edit-form.component.spec.ts
> +  });
for these methods, we should be creating a modalSpy and checking if it's called with the appropriate params, you can see admin-notifications-page.component.spec.ts for an example

2023-10-29 03:59 UTC, kenneySiu commented
Added additional tests 
Ready for review

2023-10-30 10:06 UTC, cedricongjh requested changes
thanks for adding the new tests, left a few comments!

2023-10-30 10:06 UTC, cedricongjh commented on src/web/app/components/session-edit-form/session-edit-form.component.spec.ts
> +        service.getDateInstance(moment().tz(component.model.timeZone).add(1, 'days'));
same as above here

2023-10-30 10:06 UTC, cedricongjh commented on src/web/app/components/session-edit-form/session-edit-form.component.spec.ts
> +        service.getDateInstance(moment().tz(component.model.timeZone).add(1, 'days'));
same here, let's save all the moment() calls into a const instead

2023-10-30 10:06 UTC, cedricongjh commented on src/web/app/components/session-edit-form/session-edit-form.component.spec.ts
> +    const maxTimeForSessionVisible = component.maxTimeForSessionVisible;
same as above here

2023-10-30 10:06 UTC, cedricongjh commented on src/web/app/components/session-edit-form/session-edit-form.component.spec.ts
> +        service.getDateInstance(moment().tz(component.model.timeZone));
we should make customerSessionVisibleDate different from submissionStartDate here

2023-10-30 10:06 UTC, cedricongjh commented on src/web/app/components/session-edit-form/session-edit-form.component.spec.ts
> +        service.getTimeInstance(moment().tz(component.model.timeZone));
same here, let's make the customSessionVisibleTime different from submissionStartTime

2023-10-30 11:08 UTC, kenneySiu commented
Ready for review

2023-11-01 14:26 UTC, cedricongjh approved these changes
LGTM! thank you for your work on this!

2023-12-05 14:14 UTC, weiquu approved these changes
LGTM

2023-12-05 14:14 UTC, merged