[#12048] Migrate join course action
TEAMMATES/teammates pull request #12722
Opened 2024-02-04 09:55 UTC by yuanxi1

Part of #12048

**Outline of Solution**
- Modified `JoinCourseAction` to use `sqlLogic` when course is migrated
  - Used registration key in the http param to query the DB for `courseId`. 
  - Default to use the result of querying datastore if it is not null. If both are null, default to "not migrated" instead of throwing exception as the logic for checking if registration key is valid is already present in the logic layer.
- Added `joinCourseForStudent` and `joinCourseForInstructor` to`sqllogic.core.AccountsLogic`
- Added integration test for `JoinCourseAction`
- Added test cases for testing the `joinCourseForStudent` and `joinCourseForInstructor` to `AccountsLogicIT.java`

2024-02-04 15:17 UTC, cedricongjh requested changes
some nits, but overall LGTM!

2024-02-04 15:17 UTC, cedricongjh commented on src/it/java/teammates/it/storage/sqlsearch/InstructorSearchIT.java
> +        System.out.println("🌕🌕🌕🌕🌕🌕🌕🌕" + results.size());
nit: let's remove this print statement

2024-02-04 15:17 UTC, cedricongjh commented on src/it/java/teammates/it/storage/sqlsearch/InstructorSearchIT.java
> +        System.out.println("😡" + expected.length);
nit: remove these print statements

2024-02-05 13:02 UTC, weiquu approved these changes
LGTM! Thanks

2024-02-06 07:07 UTC, cedricongjh approved these changes
LGTM, thanks!

2024-02-06 07:29 UTC, merged