[#11843] Update GetFeedbackSessionLogsAction to use SQL db
TEAMMATES/teammates pull request #12938
Opened 2024-03-26 08:09 UTC by dishenggg

Part of #11843 

**Outline of Solution**

 

- Action now retrieve logs from `FeedbackSessionLogsDB` if the course is migrated
- Added SQL unit test for `GetFeedbackSessionLogsAction`
- Added logs into databundle used for testing
- Added `FeedbackSessionLogsLogicIT`
- Updated `FeedbackSessionLogsDbIT` to use databundle
- `FeedbackSessionLogs` are set to cascade delete if their referenced `Student` or `FeedbackSession` gets deleted

2024-04-02 05:07 UTC, FergusMok requested changes
Great work, can try to keep the subsequent PRs more scoped and smaller in size

2024-04-02 05:07 UTC, FergusMok commented on src/main/java/teammates/ui/output/FeedbackSessionLogsData.java
>      // Remove generic types after migration is done (i.e. can just use FeedbackSession and Student)
Can update the comment too

2024-04-03 12:03 UTC, FergusMok approved these changes

2024-04-05 12:25 UTC, cedricongjh approved these changes
LGTM, thanks for the work on this!

2024-04-05 12:25 UTC, merged