[#12946] Initialise DDL for Course Structure
TEAMMATES/teammates pull request #12948
Opened 2024-03-27 12:54 UTC by domlimm

Part of https://github.com/TEAMMATES/teammates/issues/12946.

**Outline of Solution**
Initialise DDL for Course Structure.

2024-03-27 14:57 UTC, weiquu requested changes
@domlimm just some small changes

2024-03-27 14:57 UTC, weiquu commented on src/main/java/teammates/storage/sqlentity/Course.java
> -
This should be changed to a list of course structures, with cascade as well

2024-03-27 14:57 UTC, weiquu commented on src/main/java/teammates/storage/sqlentity/Team.java
> +    private List<TeamToStudentMap> teamToStudentMaps;
I believe we can remove this? Since we have gotten the students directly already

2024-03-27 14:57 UTC, weiquu commented on src/main/java/teammates/storage/sqlentity/Team.java
> +        this.setTeamToStudentMaps(new ArrayList<>());
Then these (including lines 109-110, 113-114, and 135 can be changed to use the set of students

2024-03-27 14:57 UTC, weiquu commented on src/main/java/teammates/storage/sqlentity/TeamToStudentMap.java
> +public class TeamToStudentMap extends BaseEntity {
missing createdAt attribute

2024-03-30 04:25 UTC, domlimm commented on src/main/java/teammates/storage/sqlentity/TeamToStudentMap.java
> +public class TeamToStudentMap extends BaseEntity {
BaseEntity contains the attribute

2024-04-04 02:41 UTC, weiquu approved these changes
LGTM

2024-04-04 02:41 UTC, merged