[#11878] Add AccountRequest Rejection email generator.
TEAMMATES/teammates pull request #12987
Opened 2024-04-06 08:33 UTC by EuniceSim142

Part of #11878.

**Outline of Solution**
Add Email-generator methods for account request rejection email.

Example (with entire content passed in as rich text):
<img width="777" alt="Screenshot 2024-04-06 at 4 30 17 PM" src="https://github.com/TEAMMATES/teammates/assets/77243938/5a108976-64ef-4135-b268-2cac6b2ad739">

2024-04-06 12:40 UTC, domoberzin reviewed
Other than the lint checks failing, code looks good to me. Thanks for the work on this!

2024-04-07 13:52 UTC, domoberzin approved these changes
LGTM!

2024-04-08 03:20 UTC, xenosf requested changes
Other than needing to BCC the support email, LGTM!

2024-04-08 03:20 UTC, xenosf commented on src/main/java/teammates/sqllogic/api/SqlEmailGenerator.java
> +    public EmailWrapper generateAccountRequestRejectionEmail(AccountRequest accountRequest, String title, String content) {
I think prof mentioned he wanted the email to be BCC-ed to the support email so the admin gets a copy as well

2024-04-08 04:39 UTC, xenosf approved these changes
LGTM. Thanks for the work!

2024-04-08 04:50 UTC, domoberzin approved these changes
LGTM

2024-04-08 04:50 UTC, merged