[#12048] Update liquibase docs
TEAMMATES/teammates pull request #13062
Opened 2024-04-19 14:58 UTC by NicolasCwy

Part of #12048

**Context**
Previously I mentioned that liquibase runs changelogs in alphanumeric order, but this is incorrect. Changelogs are run in numeric order if the [includeAll tag](https://docs.liquibase.com/change-types/includeall.html) is used to run changelogs. In Teammates, we use the [include tag](https://docs.liquibase.com/change-types/include.htm) which runs in the order they are placed in the `changelog-root.xml` file

**Outline of Solution**
Amend documentation to remind devs to add newest changelog to bottom of file.

Note: I'll update the Teammates Ops process which is more critical

2024-04-19 15:03 UTC, NicolasCwy commented
Although the changelog sorted by name is 
- `db.changelog-v9.0.0.beta.1`
- `db.changelog-v9.0.0.beta.11`
- `db.changelog-v9.0.0`

The changelog executes in the order following the `changelog-root.xml`
- `db.changelog-v9.0.0`
- `db.changelog-v9.0.0.beta.1`
- `db.changelog-v9.0.0.beta.11`

<img width="487" alt="image" src="https://github.com/TEAMMATES/teammates/assets/25302138/ca7f0280-2eff-40fd-a100-ee9d051d6295">

<img width="731" alt="image" src="https://github.com/TEAMMATES/teammates/assets/25302138/565e85c9-282c-4fe4-ac5c-553181612b12">

2024-04-20 00:52 UTC, ziqing26 requested changes
Let's change the three places (including the file name) to `-beta.5` instead of `.beta.5`

2024-04-20 00:52 UTC, ziqing26 commented on src/main/resources/db/changelog/db.changelog-root.xml
> +    <include file="src/main/resources/db/changelog/db.changelog-v9.0.0.beta.5.xml" />
```suggestion
    <include file="src/main/resources/db/changelog/db.changelog-v9.0.0-beta.5.xml" />
```

2024-04-20 00:52 UTC, ziqing26 commented on src/main/resources/db/changelog/db.changelog-v9.0.0.beta.5.xml
> +        <tagDatabase tag="v9.0.0.beta.5"/>
```suggestion
        <tagDatabase tag="v9.0.0-beta.5"/>
```

2024-04-20 02:09 UTC, ziqing26 approved these changes
Thanks for the correction! LGTM

2024-04-20 02:09 UTC, merged