[#11383] Add detection of PRs linking to closed issues
TEAMMATES/teammates pull request #13154
Opened 2024-07-27 10:55 UTC by itstrueitstrueitsrealitsreal

Part of #11383

**Outline of Solution**
Modified `pr.yml` to check for the status of the issue that newly created pull requests are solving, allowing users to be notified that the issue they are trying to work on is already closed, as per [Automation Hero](https://github.com/TEAMMATES/teammates/wiki/Automation-Hero) in the wiki. Tested on my personal fork.

2024-07-28 04:03 UTC, domoberzin requested changes
Thanks for working on this, but I think we may need to make some changes

2024-07-28 04:03 UTC, domoberzin commented on .github/workflows/pr.yml
> +            if (!isIssueOpen) {
Based on this branching, it is possible that the body contains the message for not having a `Fixes #<issue-number>` as well as the message for not addressing an open issue right? I would assume logic should work  something like this:
- If isDescriptionValid is false, it means the PR description doesn't contain a valid reference to an issue number.
- If isIssueOpen is checking whether the referenced issue is open (assuming it was implemented correctly), it wouldn't be able to perform this check if there's no valid issue reference in the description.

Based on the above, a more logical flow should look something like:

- Check if the description is valid (contains a proper issue reference)
- Only if the description is valid, then fetch and check the state of the referenced issue (I believe the issue number can be extracted using capture groups)

To use a capture group, the extraction process might look something like this (this is just an example, do test it out and verify)

```
const descriptionRegex = /(?:[Ff]ix(?:es|ed)?|[Cc]lose(?:s|d)?|[Rr]esolve(?:s|d)?|[Pp]art [Oo]f) #(\d+)/;
const extractIssueNum = (description) => {
  const match = description.match(descriptionRegex);
  return match ? match[1] : null;
};
const issueNumber = extractIssueNumber(pr.data.body);
```

2024-07-28 04:18 UTC, itstrueitstrueitsrealitsreal commented on .github/workflows/pr.yml
> +            const isIssueOpen = pr.data.state.description === 'open';
Thanks for the review @domoberzin, the link you provided was to the response for pull requests, but the workflow file queries for issues, and the schema of the response for issues are:
```json
//...

{
  "title": "Issue",
  "description": "Issues are a great way to keep track of tasks, enhancements, and bugs for your projects.",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "node_id": {
      "type": "string"
    },
    "url": {
      "description": "URL for the issue",
      "type": "string",
      "format": "uri",
      "examples": [
        "https://api.github.com/repositories/42/issues/1"
      ]
    },
    "repository_url": {
      "type": "string",
      "format": "uri"
    },
    "labels_url": {
      "type": "string"
    },
    "comments_url": {
      "type": "string",
      "format": "uri"
    },
    "events_url": {
      "type": "string",
      "format": "uri"
    },
    "html_url": {
      "type": "string",
      "format": "uri"
    },
    "number": {
      "description": "Number uniquely identifying the issue within its repository",
      "type": "integer",
      "examples": [
        42
      ]
    },
    "state": {
      "description": "State of the issue; either 'open' or 'closed'", // this is the relevant field
      "type": "string",
      "examples": [
        "open"
      ]
    },

//...



```

2024-07-28 04:22 UTC, domoberzin commented on .github/workflows/pr.yml
> +            const isIssueOpen = pr.data.state.description === 'open';
@itstrueitstrueitsrealitsreal correct me if im wrong, but the line above
```
 const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
 ```
 
 is querying for PRs, not issues right?

2024-07-28 04:27 UTC, itstrueitstrueitsrealitsreal commented on .github/workflows/pr.yml
> +            const isIssueOpen = pr.data.state.description === 'open';
Alright, I seem to have made a mistake w.r.t. to pulls and issues, will rectify this, thanks!

2024-07-28 06:36 UTC, domoberzin approved these changes
LGTM

2024-07-30 15:16 UTC, mingyuanc approved these changes
LGTM, interesting solution!

2024-07-30 15:16 UTC, merged