[#13160] Update documentation to use Docker Compose v2
TEAMMATES/teammates pull request #13161
Opened 2024-08-03 10:23 UTC by NeoHW

Fixes #13160

2024-09-02 09:34 UTC, weiquu requested changes

2024-09-02 09:34 UTC, weiquu commented on docs/development.md
> -```sh
Some comments for this particular panel section:
- "If the above command does not work, you may want to try this instead:" -> this line should be removed as well
- Let's standardise the language used, so "We have a Docker compose definition to run dependent services..." can be changed to something like "Docker Compose v2 is used to run dependent services..." (i.e. follow the change you made in line 66)

2024-09-02 09:34 UTC, weiquu commented on docs/search.md
> -If the above command does not work, you may want to try this instead:
Same comment as above, let's standardise the language used, so "We have provided a Docker compose definition to run dependent services..." can be changed to something like "Docker Compose v2 is used to run dependent services..."

2025-02-18 17:06 UTC, jasonqiu212 approved these changes
LGTM!

2025-02-27 01:31 UTC, jasonqiu212 commented
Hi @NeoHW, Would it be possible to open a new PR with these changes to merge in this fix sooner? 

I am unable to merge this current PR currently, because @weiquu requested changes and I am not sure if he is available anytime soon. Apologies for the inconvenience!

2025-02-27 02:31 UTC, merged