[#13104] Add mappings
TEAMMATES/teammates pull request #13166
Opened 2024-08-08 17:21 UTC by itstrueitstrueitsrealitsreal

Fixes #13104

**Outline of Solution**

Made the dictionary of mappings in [3f5f68d](https://github.com/TEAMMATES/teammates/commit/3f5f68dc971ebabc2eb0f5d8541a24b36d716807) more extensive, covering more countries and cases.

Updated mappings:
```javascript
    const countryMapping: { [key: string]: string } = {
      'united states': 'USA',
      'u.s.a': 'USA',
      'us': 'USA',
      'america': 'USA',
      'united states of america': 'USA',

      'united kingdom': 'UK',
      'uk': 'UK',
      'britain': 'UK',
      'great britain': 'UK',
      'england': 'UK',

      'united arab emirates': 'UAE',
      'uae': 'UAE',
      'emirates': 'UAE',

      'deutschland': 'Germany',
      'germany': 'Germany',

      'netherlands': 'Netherlands',
      'holland': 'Netherlands',

      'belgium': 'Belgium',
      'belgië': 'Belgium',
      'belgique': 'Belgium',

      'brazil': 'Brazil',
      'brasil': 'Brazil',

      'spain': 'Spain',
      'españa': 'Spain',

      'mexico': 'Mexico',
      'méxico': 'Mexico',

      'italy': 'Italy',
      'italia': 'Italy',

      'china': 'China',
      'peoples republic of china': 'China',
      'prc': 'China',

      'france': 'France',
      'republic of france': 'France',

      'india': 'India',
      'bharat': 'India',

      'japan': 'Japan',
      'nippon': 'Japan',

      'russia': 'Russia',
      'russian federation': 'Russia',

      'south korea': 'South Korea',
      'republic of korea': 'South Korea',
      'korea': 'South Korea',

      'north korea': 'North Korea',
      'democratic peoples republic of korea': 'North Korea',

      'south africa': 'South Africa',
      'republic of south africa': 'South Africa',

      'switzerland': 'Switzerland',
      'schweiz': 'Switzerland',
      'suisse': 'Switzerland',
      'svizzera': 'Switzerland',
      'svizra': 'Switzerland',

      'taiwan': 'Taiwan',
      'republic of china': 'Taiwan',

      'turkey': 'Turkey',
      'republic of turkey': 'Turkey',

      'vietnam': 'Vietnam',
      'viet nam': 'Vietnam',
    };
```

2024-08-09 03:44 UTC, damithc requested changes
Some suggestions ...

Also add Malaysia and France, as often I find people typing them in ALL CAPS.

2024-08-09 03:44 UTC, damithc commented on src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
> +      netherlands: 'Netherlands',
Also add `the netherlands` and `nederland`

2024-08-09 03:44 UTC, damithc commented on src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
> +      bharat: 'India',
```suggestion
      india: 'India',
```

2024-08-09 03:44 UTC, damithc commented on src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
> +      nippon: 'Japan',
```suggestion
      japan: 'Japan',
```

2024-08-09 03:44 UTC, damithc commented on src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
> +      svizra: 'Switzerland',
```suggestion
      switzerland: 'Switzerland',
```

2024-08-09 03:44 UTC, damithc commented on src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
> +      'republic of china': 'Taiwan',
```suggestion
      taiwan: 'Taiwan',
```

2024-08-09 03:44 UTC, damithc commented on src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
> +      'republic of turkey': 'Turkey',
Also add `Republic of Türkiye`

2024-08-09 03:44 UTC, damithc commented on src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
> +      belgique: 'Belgium',
```suggestion
      belgium: 'Belgium',
      belgië: 'Belgium',
```

2024-08-09 15:44 UTC, itstrueitstrueitsrealitsreal commented
Updated the mappings according to suggestions, marked for review.

2024-09-22 07:44 UTC, damithc requested changes
I'm OK with the updates, except the one entry I've commented on.

2024-09-22 07:44 UTC, damithc commented on src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
> +      taiwan: 'Taiwan',
Let's remove this one.

2024-09-22 08:56 UTC, itstrueitstrueitsrealitsreal commented on src/web/app/pages-static/request-page/instructor-request-form/instructor-request-form.component.ts
> +      taiwan: 'Taiwan',
Fixed!

2025-02-15 11:52 UTC, jasonqiu212 approved these changes
LGTM! Apologies for the delay, and thank you for contributing to TEAMMATES!

2025-02-16 03:37 UTC, damithc approved these changes
LGTM. Thanks @itstrueitstrueitsrealitsreal for this PR.

2025-02-16 06:53 UTC, merged